In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style='ticks', palette='Set3')

In [5]:
# JSON
import json

In [6]:
#reading in text version of a json file of data for open and close prices of Apple stock
with open("/Users/marshallringwood/Desktop/ECON213R/aapl.txt", "r") as f:
    aapl_df = json.load(f)
aapl_df

[{'close': 33.5, 'date': '1994-01-26', 'open': 33.75},
 {'close': 34.13, 'date': '1994-01-27', 'open': 33.5},
 {'close': 34.0, 'date': '1994-01-28', 'open': 34.25},
 {'close': 32.75, 'date': '1994-01-31', 'open': 33.5},
 {'close': 33.25, 'date': '1994-02-01', 'open': 33.0},
 {'close': 33.0, 'date': '1994-02-02', 'open': 33.25},
 {'close': 33.5, 'date': '1994-02-03', 'open': 33.0},
 {'close': 33.5, 'date': '1994-02-04', 'open': 33.5},
 {'close': 36.5, 'date': '1994-02-07', 'open': 33.5},
 {'close': 35.75, 'date': '1994-02-08', 'open': 36.0},
 {'close': 36.25, 'date': '1994-02-09', 'open': 35.75},
 {'close': 36.5, 'date': '1994-02-10', 'open': 36.25},
 {'close': 37.0, 'date': '1994-02-11', 'open': 36.25},
 {'close': 37.0, 'date': '1994-02-14', 'open': 37.0},
 {'close': 37.13, 'date': '1994-02-15', 'open': 36.75},
 {'close': 36.75, 'date': '1994-02-16', 'open': 37.5},
 {'close': 37.0, 'date': '1994-02-17', 'open': 37.25},
 {'close': 36.25, 'date': '1994-02-18', 'open': 36.5},
 {'close': 37.25, 'date': '1994-02-22', 'open': 36.25},
 {'close': 37.25, 'date': '1994-02-23', 'open': 37.25},
 {'close': 36.63, 'date': '1994-02-24', 'open': 37.0},
 {'close': 36.0, 'date': '1994-02-25', 'open': 37.0},
 {'close': 36.5, 'date': '1994-02-28', 'open': 36.25},
 {'close': 36.25, 'date': '1994-03-01', 'open': 36.75},
 {'close': 35.63, 'date': '1994-03-02', 'open': 35.25},
 {'close': 35.75, 'date': '1994-03-03', 'open': 35.75},
 {'close': 36.75, 'date': '1994-03-04', 'open': 36.0},
 {'close': 37.88, 'date': '1994-03-07', 'open': 37.0},
 {'close': 37.0, 'date': '1994-03-08', 'open': 38.0},
 {'close': 37.5, 'date': '1994-03-09', 'open': 36.63},
 {'close': 37.25, 'date': '1994-03-10', 'open': 37.25},
 {'close': 37.25, 'date': '1994-03-11', 'open': 37.0},
 {'close': 38.13, 'date': '1994-03-14', 'open': 38.5},
 {'close': 37.63, 'date': '1994-03-15', 'open': 38.25},
 {'close': 36.75, 'date': '1994-03-16', 'open': 37.5},
 {'close': 36.5, 'date': '1994-03-17', 'open': 36.75},
 {'close': 36.38, 'date': '1994-03-18', 'open': 36.75},
 {'close': 35.5, 'date': '1994-03-21', 'open': 36.38},
 {'close': 35.0, 'date': '1994-03-22', 'open': 35.25},
 {'close': 35.13, 'date': '1994-03-23', 'open': 35.25},
 {'close': 34.63, 'date': '1994-03-24', 'open': 35.13},
 {'close': 32.75, 'date': '1994-03-25', 'open': 34.75},
 {'close': 33.25, 'date': '1994-03-28', 'open': 33.0},
 {'close': 32.75, 'date': '1994-03-29', 'open': 33.25},
 {'close': 32.5, 'date': '1994-03-30', 'open': 32.5},
 {'close': 33.25, 'date': '1994-03-31', 'open': 32.5},
 {'close': 33.25, 'date': '1994-04-04', 'open': 32.25},
 {'close': 33.5, 'date': '1994-04-05', 'open': 33.75},
 {'close': 33.5, 'date': '1994-04-06', 'open': 34.0},
 {'close': 33.38, 'date': '1994-04-07', 'open': 33.5},
 {'close': 33.5, 'date': '1994-04-08', 'open': 33.75},
 {'close': 33.5, 'date': '1994-04-11', 'open': 33.5},
 {'close': 32.0, 'date': '1994-04-12', 'open': 33.38},
 {'close': 31.75, 'date': '1994-04-13', 'open': 32.25},
 {'close': 31.5, 'date': '1994-04-14', 'open': 30.5},
 {'close': 30.25, 'date': '1994-04-15', 'open': 31.25},
 {'close': 29.62, 'date': '1994-04-18', 'open': 30.5},
 {'close': 29.0, 'date': '1994-04-19', 'open': 29.75},
 {'close': 28.25, 'date': '1994-04-20', 'open': 29.25},
 {'close': 29.62, 'date': '1994-04-21', 'open': 28.5},
 {'close': 29.75, 'date': '1994-04-22', 'open': 31.25},
 {'close': 31.0, 'date': '1994-04-25', 'open': 29.75},
 {'close': 31.25, 'date': '1994-04-26', 'open': 31.5},
 {'close': 30.25, 'date': '1994-04-28', 'open': 31.0},
 {'close': 30.0, 'date': '1994-04-29', 'open': 30.0},
 {'close': 31.0, 'date': '1994-05-02', 'open': 30.0},
 {'close': 30.25, 'date': '1994-05-03', 'open': 31.0},
 {'close': 33.0, 'date': '1994-05-04', 'open': 31.0},
 {'close': 32.88, 'date': '1994-05-05', 'open': 33.25},
 {'close': 32.31, 'date': '1994-05-06', 'open': 32.25},
 {'close': 31.25, 'date': '1994-05-09', 'open': 32.25},
 {'close': 31.0, 'date': '1994-05-10', 'open': 31.75},
 {'close': 30.25, 'date': '1994-05-11', 'open': 31.0},
 {'close': 29.69, 'date': '1994-05-12', 'open': 30.5},
 {'close': 30.0, 'date': '1994-05-13', 'open': 29.75},
 {'close': 29.5, 'date': '1994-05-16', 'open': 30.0},
 {'close': 29.37, 'date': '1994-05-17', 'open': 29.75},
 {'close': 30.62, 'date': '1994-05-18', 'open': 29.75},
 {'close': 32.13, 'date': '1994-05-19', 'open': 30.75},
 {'close': 31.06, 'date': '1994-05-20', 'open': 31.75},
 {'close': 30.5, 'date': '1994-05-23', 'open': 31.0},
 {'close': 30.75, 'date': '1994-05-24', 'open': 31.0},
 {'close': 31.25, 'date': '1994-05-25', 'open': 30.25},
 {'close': 30.5, 'date': '1994-05-26', 'open': 31.5},
 {'close': 29.94, 'date': '1994-05-27', 'open': 30.25},
 {'close': 29.25, 'date': '1994-05-31', 'open': 29.5},
 {'close': 28.25, 'date': '1994-06-01', 'open': 28.5},
 {'close': 27.37, 'date': '1994-06-02', 'open': 28.37},
 {'close': 27.62, 'date': '1994-06-03', 'open': 27.12},
 {'close': 27.37, 'date': '1994-06-06', 'open': 27.5},
 {'close': 27.5, 'date': '1994-06-07', 'open': 27.25},
 {'close': 26.12, 'date': '1994-06-08', 'open': 27.5},
 {'close': 27.0, 'date': '1994-06-09', 'open': 25.62},
 {'close': 26.5, 'date': '1994-06-10', 'open': 27.12},
 {'close': 27.0, 'date': '1994-06-13', 'open': 26.37},
 {'close': 27.06, 'date': '1994-06-14', 'open': 27.25},
 {'close': 27.81, 'date': '1994-06-15', 'open': 27.0},
 {'close': 26.37, 'date': '1994-06-16', 'open': 27.75},
 {'close': 26.5, 'date': '1994-06-17', 'open': 26.0},
 {'close': 27.12, 'date': '1994-06-20', 'open': 26.25},
 {'close': 26.0, 'date': '1994-06-21', 'open': 26.87},
 {'close': 26.25, 'date': '1994-06-22', 'open': 26.25},
 {'close': 25.12, 'date': '1994-06-23', 'open': 26.25},
 {'close': 25.61, 'date': '1994-06-24', 'open': 25.12},
 {'close': 26.25, 'date': '1994-06-27', 'open': 25.25},
 {'close': 26.75, 'date': '1994-06-28', 'open': 26.25},
 {'close': 26.12, 'date': '1994-06-29', 'open': 26.75},
 {'close': 26.5, 'date': '1994-06-30', 'open': 26.25},
 {'close': 25.75, 'date': '1994-07-01', 'open': 26.37},
 {'close': 26.5, 'date': '1994-07-05', 'open': 25.62},
 {'close': 26.12, 'date': '1994-07-06', 'open': 26.25},
 {'close': 26.81, 'date': '1994-07-07', 'open': 25.87},
 {'close': 27.06, 'date': '1994-07-08', 'open': 26.5},
 {'close': 27.0, 'date': '1994-07-11', 'open': 27.12},
 {'close': 28.37, 'date': '1994-07-12', 'open': 27.0},
 {'close': 29.69, 'date': '1994-07-13', 'open': 28.5},
 {'close': 28.62, 'date': '1994-07-14', 'open': 29.62},
 {'close': 28.25, 'date': '1994-07-15', 'open': 28.23},
 {'close': 28.37, 'date': '1994-07-18', 'open': 28.12},
 {'close': 27.69, 'date': '1994-07-19', 'open': 28.62},
 {'close': 26.62, 'date': '1994-07-20', 'open': 27.37},
 {'close': 28.0, 'date': '1994-07-21', 'open': 26.62},
 {'close': 31.0, 'date': '1994-07-22', 'open': 31.62},
 {'close': 31.69, 'date': '1994-07-25', 'open': 31.12},
 {'close': 31.37, 'date': '1994-07-26', 'open': 31.75},
 {'close': 31.06, 'date': '1994-07-27', 'open': 31.25},
 {'close': 31.87, 'date': '1994-07-28', 'open': 31.0},
 {'close': 33.69, 'date': '1994-07-29', 'open': 31.87},
 {'close': 33.38, 'date': '1994-08-01', 'open': 33.63},
 {'close': 32.56, 'date': '1994-08-02', 'open': 33.5},
 {'close': 33.13, 'date': '1994-08-03', 'open': 32.75},
 {'close': 33.25, 'date': '1994-08-04', 'open': 33.13},
 {'close': 33.25, 'date': '1994-08-05', 'open': 32.88},
 {'close': 33.75, 'date': '1994-08-08', 'open': 33.13},
 {'close': 33.63, 'date': '1994-08-09', 'open': 33.5},
 {'close': 34.63, 'date': '1994-08-10', 'open': 33.63},
 {'close': 34.31, 'date': '1994-08-11', 'open': 34.25},
 {'close': 34.75, 'date': '1994-08-12', 'open': 34.38},
 {'close': 34.63, 'date': '1994-08-15', 'open': 34.75},
 {'close': 34.75, 'date': '1994-08-16', 'open': 34.38},
 {'close': 35.0, 'date': '1994-08-17', 'open': 34.88},
 {'close': 34.63, 'date': '1994-08-18', 'open': 34.75},
 {'close': 34.88, 'date': '1994-08-19', 'open': 34.75},
 {'close': 34.88, 'date': '1994-08-22', 'open': 34.75},
 {'close': 35.0, 'date': '1994-08-23', 'open': 34.88},
 {'close': 34.88, 'date': '1994-08-24', 'open': 34.75},
 {'close': 35.06, 'date': '1994-08-25', 'open': 34.25},
 {'close': 35.75, 'date': '1994-08-26', 'open': 35.25},
 {'close': 35.38, 'date': '1994-08-29', 'open': 35.75},
 {'close': 36.25, 'date': '1994-08-30', 'open': 35.25},
 {'close': 36.19, 'date': '1994-08-31', 'open': 36.0},
 {'close': 35.0, 'date': '1994-09-01', 'open': 35.38},
 {'close': 35.38, 'date': '1994-09-02', 'open': 35.25},
 {'close': 35.56, 'date': '1994-09-06', 'open': 35.25},
 {'close': 36.13, 'date': '1994-09-07', 'open': 35.63},
 {'close': 36.13, 'date': '1994-09-08', 'open': 36.0},
 {'close': 35.75, 'date': '1994-09-09', 'open': 35.75},
 {'close': 35.75, 'date': '1994-09-12', 'open': 35.63},
 {'close': 35.81, 'date': '1994-09-13', 'open': 35.75},
 {'close': 35.13, 'date': '1994-09-14', 'open': 35.63},
 {'close': 36.0, 'date': '1994-09-15', 'open': 35.13},
 {'close': 36.38, 'date': '1994-09-16', 'open': 35.88},
 {'close': 35.5, 'date': '1994-09-19', 'open': 36.38},
 {'close': 34.56, 'date': '1994-09-20', 'open': 35.13},
 {'close': 34.13, 'date': '1994-09-21', 'open': 34.5},
 {'close': 33.88, 'date': '1994-09-22', 'open': 34.25},
 {'close': 33.94, 'date': '1994-09-23', 'open': 33.88},
 {'close': 33.94, 'date': '1994-09-26', 'open': 33.88},
 {'close': 33.88, 'date': '1994-09-27', 'open': 33.75},
 {'close': 33.88, 'date': '1994-09-28', 'open': 34.0},
 {'close': 34.13, 'date': '1994-09-29', 'open': 33.75},
 {'close': 33.69, 'date': '1994-09-30', 'open': 34.13},
 {'close': 33.13, 'date': '1994-10-03', 'open': 33.63},
 {'close': 33.75, 'date': '1994-10-04', 'open': 33.25},
 {'close': 37.88, 'date': '1994-10-05', 'open': 33.63},
 {'close': 36.25, 'date': '1994-10-06', 'open': 37.38},
 {'close': 37.0, 'date': '1994-10-07', 'open': 36.13},
 {'close': 38.88, 'date': '1994-10-10', 'open': 37.13},
 {'close': 39.63, 'date': '1994-10-11', 'open': 41.38},
 {'close': 42.13, 'date': '1994-10-12', 'open': 39.63},
 {'close': 41.13, 'date': '1994-10-13', 'open': 42.63},
 {'close': 41.13, 'date': '1994-10-14', 'open': 41.5},
 {'close': 39.75, 'date': '1994-10-17', 'open': 40.88},
 {'close': 41.25, 'date': '1994-10-18', 'open': 40.63},
 {'close': 41.25, 'date': '1994-10-19', 'open': 41.0},
 {'close': 41.0, 'date': '1994-10-20', 'open': 41.25},
 {'close': 42.63, 'date': '1994-10-21', 'open': 40.75},
 {'close': 42.25, 'date': '1994-10-24', 'open': 42.75},
 {'close': 42.63, 'date': '1994-10-25', 'open': 41.63},
 {'close': 43.25, 'date': '1994-10-26', 'open': 42.63},
 {'close': 42.75, 'date': '1994-10-27', 'open': 43.25},
 {'close': 42.13, 'date': '1994-10-28', 'open': 42.38},
 {'close': 43.19, 'date': '1994-10-31', 'open': 42.0},
 {'close': 43.13, 'date': '1994-11-01', 'open': 42.88},
 {'close': 41.38, 'date': '1994-11-02', 'open': 43.13},
 {'close': 41.5, 'date': '1994-11-03', 'open': 41.75},
 {'close': 40.38, 'date': '1994-11-04', 'open': 41.5},
 {'close': 40.75, 'date': '1994-11-07', 'open': 40.38},
 {'close': 42.25, 'date': '1994-11-08', 'open': 40.63},
 {'close': 41.63, 'date': '1994-11-09', 'open': 42.75},
 {'close': 41.31, 'date': '1994-11-10', 'open': 41.75},
 {'close': 41.13, 'date': '1994-11-11', 'open': 41.25},
 {'close': 42.5, 'date': '1994-11-14', 'open': 41.25},
 {'close': 41.38, 'date': '1994-11-15', 'open': 42.5},
 {'close': 40.94, 'date': '1994-11-16', 'open': 40.75},
 {'close': 40.0, 'date': '1994-11-17', 'open': 40.88},
 {'close': 40.0, 'date': '1994-11-18', 'open': 40.0},
 {'close': 38.13, 'date': '1994-11-21', 'open': 40.0},
 {'close': 37.38, 'date': '1994-11-22', 'open': 37.75},
 {'close': 36.88, 'date': '1994-11-23', 'open': 37.0},
 {'close': 37.75, 'date': '1994-11-25', 'open': 36.88},
 {'close': 37.81, 'date': '1994-11-28', 'open': 37.63},
 {'close': 38.25, 'date': '1994-11-29', 'open': 38.0},
 {'close': 37.25, 'date': '1994-11-30', 'open': 38.38},
 {'close': 36.19, 'date': '1994-12-01', 'open': 37.0},
 {'close': 36.56, 'date': '1994-12-02', 'open': 36.5},
 {'close': 37.19, 'date': '1994-12-05', 'open': 36.5},
 {'close': 37.56, 'date': '1994-12-06', 'open': 37.0},
 {'close': 36.63, 'date': '1994-12-07', 'open': 37.5},
 {'close': 35.88, 'date': '1994-12-08', 'open': 36.88},
 {'close': 36.25, 'date': '1994-12-09', 'open': 35.88},
 {'close': 36.5, 'date': '1994-12-12', 'open': 36.38},
 {'close': 36.38, 'date': '1994-12-13', 'open': 36.63},
 {'close': 37.88, 'date': '1994-12-14', 'open': 36.5},
 {'close': 37.13, 'date': '1994-12-15', 'open': 38.0},
 {'close': 37.25, 'date': '1994-12-16', 'open': 37.25},
 {'close': 39.13, 'date': '1994-12-19', 'open': 37.25},
 {'close': 38.5, 'date': '1994-12-20', 'open': 39.13},
 {'close': 38.38, 'date': '1994-12-21', 'open': 37.88},
 {'close': 38.63, 'date': '1994-12-22', 'open': 38.5},
 {'close': 38.88, 'date': '1994-12-23', 'open': 38.5},
 {'close': 39.13, 'date': '1994-12-27', 'open': 39.25},
 {'close': 39.13, 'date': '1994-12-28', 'open': 39.13},
 {'close': 39.5, 'date': '1994-12-29', 'open': 39.25},
 {'close': 39.0, 'date': '1994-12-30', 'open': 39.38},
 {'close': 38.38, 'date': '1995-01-03', 'open': 38.88},
 {'close': 39.38, 'date': '1995-01-04', 'open': 38.63},
 {'close': 38.88, 'date': '1995-01-05', 'open': 39.25},
 {'close': 42.0, 'date': '1995-01-06', 'open': 41.63},
 {'close': 41.2, 'date': '1995-01-09', 'open': 41.63},
 {'close': 43.69, 'date': '1995-01-10', 'open': 41.25},
 {'close': 46.75, 'date': '1995-01-11', 'open': 43.75},
 {'close': 45.38, 'date': '1995-01-12', 'open': 46.13},
 {'close': 44.88, 'date': '1995-01-13', 'open': 46.13},
 {'close': 44.5, 'date': '1995-01-16', 'open': 44.88},
 {'close': 45.0, 'date': '1995-01-17', 'open': 44.5},
 {'close': 45.63, 'date': '1995-01-18', 'open': 45.0},
 {'close': 45.88, 'date': '1995-01-19', 'open': 45.5},
 {'close': 42.63, 'date': '1995-01-20', 'open': 47.0},
 {'close': 42.25, 'date': '1995-01-23', 'open': 41.88},
 {'close': 41.63, 'date': '1995-01-24', 'open': 42.25},
 {'close': 40.98, 'date': '1995-01-25', 'open': 39.5},
 {'close': 39.5, 'date': '1995-01-26', 'open': 40.88},
 {'close': 39.88, 'date': '1995-01-27', 'open': 39.88},
 {'close': 40.13, 'date': '1995-01-30', 'open': 40.13},
 {'close': 40.38, 'date': '1995-01-31', 'open': 40.5},
 {'close': 40.13, 'date': '1995-02-01', 'open': 40.75},
 {'close': 41.63, 'date': '1995-02-02', 'open': 40.13},
 {'close': 40.5, 'date': '1995-02-03', 'open': 42.0},
 {'close': 40.5, 'date': '1995-02-06', 'open': 40.75},
 {'close': 40.81, 'date': '1995-02-07', 'open': 40.38},
 {'close': 42.31, 'date': '1995-02-08', 'open': 41.0},
 {'close': 43.63, 'date': '1995-02-09', 'open': 42.13},
 {'close': 43.75, 'date': '1995-02-10', 'open': 43.63},
 {'close': 43.75, 'date': '1995-02-13', 'open': 43.5},
 {'close': 42.94, 'date': '1995-02-14', 'open': 43.75},
 {'close': 42.56, 'date': '1995-02-15', 'open': 43.25},
 {'close': 43.19, 'date': '1995-02-16', 'open': 43.13},
 {'close': 42.5, 'date': '1995-02-17', 'open': 42.88},
 {'close': 41.0, 'date': '1995-02-21', 'open': 42.63},
 {'close': 40.81, 'date': '1995-02-22', 'open': 40.63},
 {'close': 40.19, 'date': '1995-02-23', 'open': 41.13},
 {'close': 39.0, 'date': '1995-02-24', 'open': 40.13},
 {'close': 38.25, 'date': '1995-02-27', 'open': 38.25},
 {'close': 39.5, 'date': '1995-02-28', 'open': 38.5},
 {'close': 40.0, 'date': '1995-03-01', 'open': 39.75},
 {'close': 40.0, 'date': '1995-03-02', 'open': 40.13},
 {'close': 40.25, 'date': '1995-03-03', 'open': 39.75},
 {'close': 39.75, 'date': '1995-03-06', 'open': 39.75},
 {'close': 38.31, 'date': '1995-03-07', 'open': 39.88},
 {'close': 39.56, 'date': '1995-03-08', 'open': 38.75},
 {'close': 39.75, 'date': '1995-03-09', 'open': 39.88},
 {'close': 39.5, 'date': '1995-03-10', 'open': 39.63},
 {'close': 38.13, 'date': '1995-03-13', 'open': 39.63},
 {'close': 35.0, 'date': '1995-03-14', 'open': 38.25},
 {'close': 35.0, 'date': '1995-03-15', 'open': 35.5},
 {'close': 35.25, 'date': '1995-03-16', 'open': 35.25},
 {'close': 35.13, 'date': '1995-03-17', 'open': 35.5},
 {'close': 35.25, 'date': '1995-03-20', 'open': 35.13},
 {'close': 36.25, 'date': '1995-03-21', 'open': 35.5},
 {'close': 38.06, 'date': '1995-03-22', 'open': 36.25},
 {'close': 37.13, 'date': '1995-03-23', 'open': 37.88},
 {'close': 37.75, 'date': '1995-03-24', 'open': 37.38},
 {'close': 37.19, 'date': '1995-03-27', 'open': 37.63},
 {'close': 34.38, 'date': '1995-03-28', 'open': 36.25},
 {'close': 34.38, 'date': '1995-03-29', 'open': 34.0},
 {'close': 35.38, 'date': '1995-03-30', 'open': 34.63},
 {'close': 35.25, 'date': '1995-03-31', 'open': 35.13},
 {'close': 35.5, 'date': '1995-04-03', 'open': 35.5},
 {'close': 33.88, 'date': '1995-04-04', 'open': 35.75},
 {'close': 34.75, 'date': '1995-04-05', 'open': 34.13},
 {'close': 36.75, 'date': '1995-04-06', 'open': 37.25},
 {'close': 36.75, 'date': '1995-04-07', 'open': 37.0},
 {'close': 36.63, 'date': '1995-04-10', 'open': 36.88},
 {'close': 37.75, 'date': '1995-04-11', 'open': 36.75},
 {'close': 39.0, 'date': '1995-04-12', 'open': 38.25},
 {'close': 38.25, 'date': '1995-04-13', 'open': 39.25},
 {'close': 38.38, 'date': '1995-04-17', 'open': 38.13},
 {'close': 37.5, 'date': '1995-04-18', 'open': 38.5},
 {'close': 36.38, 'date': '1995-04-19', 'open': 37.5},
 {'close': 37.63, 'date': '1995-04-20', 'open': 37.13},
 {'close': 39.13, 'date': '1995-04-21', 'open': 37.25},
 {'close': 39.0, 'date': '1995-04-24', 'open': 39.0},
 {'close': 37.75, 'date': '1995-04-25', 'open': 39.13},
 {'close': 38.25, 'date': '1995-04-26', 'open': 37.63},
 {'close': 37.88, 'date': '1995-04-27', 'open': 38.5},
 {'close': 38.25, 'date': '1995-04-28', 'open': 38.0},
 {'close': 38.25, 'date': '1995-05-01', 'open': 38.25},
 {'close': 38.13, 'date': '1995-05-02', 'open': 38.25},
 {'close': 38.13, 'date': '1995-05-03', 'open': 38.25},
 {'close': 38.5, 'date': '1995-05-04', 'open': 38.25},
 {'close': 38.88, 'date': '1995-05-05', 'open': 38.75},
 {'close': 40.5, 'date': '1995-05-08', 'open': 39.88},
 {'close': 41.25, 'date': '1995-05-09', 'open': 40.63},
 {'close': 41.44, 'date': '1995-05-10', 'open': 41.5},
 {'close': 41.0, 'date': '1995-05-11', 'open': 41.63},
 {'close': 43.63, 'date': '1995-05-12', 'open': 40.88},
 {'close': 43.63, 'date': '1995-05-15', 'open': 43.13},
 {'close': 43.75, 'date': '1995-05-16', 'open': 43.13},
 {'close': 44.0, 'date': '1995-05-17', 'open': 43.75},
 {'close': 43.38, 'date': '1995-05-18', 'open': 44.13},
 {'close': 42.75, 'date': '1995-05-19', 'open': 42.88},
 {'close': 44.13, 'date': '1995-05-22', 'open': 42.5},
 {'close': 43.88, 'date': '1995-05-23', 'open': 44.13},
 {'close': 43.5, 'date': '1995-05-24', 'open': 43.75},
 {'close': 43.38, 'date': '1995-05-25', 'open': 43.25},
 {'close': 42.69, 'date': '1995-05-26', 'open': 43.0},
 {'close': 42.0, 'date': '1995-05-30', 'open': 42.63},
 {'close': 41.56, 'date': '1995-05-31', 'open': 42.13},
 {'close': 42.19, 'date': '1995-06-01', 'open': 41.88},
 {'close': 42.13, 'date': '1995-06-02', 'open': 41.88},
 {'close': 43.5, 'date': '1995-06-05', 'open': 42.38},
 {'close': 44.0, 'date': '1995-06-06', 'open': 43.63},
 {'close': 43.13, 'date': '1995-06-07', 'open': 44.13},
 {'close': 42.94, 'date': '1995-06-08', 'open': 43.38},
 {'close': 43.5, 'date': '1995-06-09', 'open': 43.63},
 {'close': 44.17, 'date': '1995-06-12', 'open': 44.0},
 {'close': 44.0, 'date': '1995-06-13', 'open': 44.5},
 {'close': 43.63, 'date': '1995-06-14', 'open': 43.88},
 {'close': 43.63, 'date': '1995-06-15', 'open': 43.63},
 {'close': 43.88, 'date': '1995-06-16', 'open': 43.88},
 {'close': 44.38, 'date': '1995-06-19', 'open': 43.88},
 {'close': 47.38, 'date': '1995-06-20', 'open': 46.0},
 {'close': 49.38, 'date': '1995-06-21', 'open': 47.63},
 {'close': 49.13, 'date': '1995-06-22', 'open': 49.0},
 {'close': 48.75, 'date': '1995-06-23', 'open': 48.75},
 {'close': 48.13, 'date': '1995-06-26', 'open': 48.25},
 {'close': 46.38, 'date': '1995-06-27', 'open': 47.38},
 {'close': 46.63, 'date': '1995-06-28', 'open': 46.0},
 {'close': 47.25, 'date': '1995-06-29', 'open': 46.38},

In [7]:
import pandas as pd
series = pd.Series(aapl_df)

In [8]:
print(series)

0       {'date': '1994-01-26', 'open': 33.75, 'close':...
1       {'date': '1994-01-27', 'open': 33.5, 'close': ...
2       {'date': '1994-01-28', 'open': 34.25, 'close':...
3       {'date': '1994-01-31', 'open': 33.5, 'close': ...
4       {'date': '1994-02-01', 'open': 33.0, 'close': ...
5       {'date': '1994-02-02', 'open': 33.25, 'close':...
6       {'date': '1994-02-03', 'open': 33.0, 'close': ...
7       {'date': '1994-02-04', 'open': 33.5, 'close': ...
8       {'date': '1994-02-07', 'open': 33.5, 'close': ...
9       {'date': '1994-02-08', 'open': 36.0, 'close': ...
10      {'date': '1994-02-09', 'open': 35.75, 'close':...
11      {'date': '1994-02-10', 'open': 36.25, 'close':...
12      {'date': '1994-02-11', 'open': 36.25, 'close':...
13      {'date': '1994-02-14', 'open': 37.0, 'close': ...
14      {'date': '1994-02-15', 'open': 36.75, 'close':...
15      {'date': '1994-02-16', 'open': 37.5, 'close': ...
16      {'date': '1994-02-17', 'open': 37.25, 'close':...
17      {'date': '1994-02-18', 'open': 36.5, 'close': ...
18      {'date': '1994-02-22', 'open': 36.25, 'close':...
19      {'date': '1994-02-23', 'open': 37.25, 'close':...
20      {'date': '1994-02-24', 'open': 37.0, 'close': ...
21      {'date': '1994-02-25', 'open': 37.0, 'close': ...
22      {'date': '1994-02-28', 'open': 36.25, 'close':...
23      {'date': '1994-03-01', 'open': 36.75, 'close':...
24      {'date': '1994-03-02', 'open': 35.25, 'close':...
25      {'date': '1994-03-03', 'open': 35.75, 'close':...
26      {'date': '1994-03-04', 'open': 36.0, 'close': ...
27      {'date': '1994-03-07', 'open': 37.0, 'close': ...
28      {'date': '1994-03-08', 'open': 38.0, 'close': ...
29      {'date': '1994-03-09', 'open': 36.63, 'close':...
                              ...
5892    {'date': '2017-06-21', 'open': 145.52, 'close'...
5893    {'date': '2017-06-22', 'open': 145.77, 'close'...
5894    {'date': '2017-06-23', 'open': 145.13, 'close'...
5895    {'date': '2017-06-26', 'open': 147.17, 'close'...
5896    {'date': '2017-06-27', 'open': 145.01, 'close'...
5897    {'date': '2017-06-28', 'open': 144.49, 'close'...
5898    {'date': '2017-06-29', 'open': 144.71, 'close'...
5899    {'date': '2017-06-30', 'open': 144.45, 'close'...
5900    {'date': '2017-07-03', 'open': 144.88, 'close'...
5901    {'date': '2017-07-05', 'open': 143.69, 'close'...
5902    {'date': '2017-07-06', 'open': 143.02, 'close'...
5903    {'date': '2017-07-07', 'open': 142.9, 'close':...
5904    {'date': '2017-07-10', 'open': 144.11, 'close'...
5905    {'date': '2017-07-11', 'open': 144.73, 'close'...
5906    {'date': '2017-07-12', 'open': 145.87, 'close'...
5907    {'date': '2017-07-13', 'open': 145.5, 'close':...
5908    {'date': '2017-07-14', 'open': 147.97, 'close'...
5909    {'date': '2017-07-17', 'open': 148.82, 'close'...
5910    {'date': '2017-07-18', 'open': 149.2, 'close':...
5911    {'date': '2017-07-19', 'open': 150.48, 'close'...
5912    {'date': '2017-07-20', 'open': 151.5, 'close':...
5913    {'date': '2017-07-21', 'open': 149.99, 'close'...
5914    {'date': '2017-07-24', 'open': 150.58, 'close'...
5915    {'date': '2017-07-25', 'open': 151.8, 'close':...
5916    {'date': '2017-07-26', 'open': 153.35, 'close'...
5917    {'date': '2017-07-27', 'open': 153.75, 'close'...
5918    {'date': '2017-07-28', 'open': 149.89, 'close'...
5919    {'date': '2017-07-31', 'open': 149.9, 'close':...
5920    {'date': '2017-08-01', 'open': 149.1, 'close':...
5921    {'date': '2017-08-02', 'open': 159.28, 'close'...
Length: 5922, dtype: object

In [27]:
#turning json into a "normal" data frame
aapl_df = pd.DataFrame.from_dict(aapl_df, orient='columns')
aapl_df
pd.set_option('display.max_rows', 100)
print(aapl_df)

       close        date    open
0      33.50  1994-01-26   33.75
1      34.13  1994-01-27   33.50
2      34.00  1994-01-28   34.25
3      32.75  1994-01-31   33.50
4      33.25  1994-02-01   33.00
5      33.00  1994-02-02   33.25
6      33.50  1994-02-03   33.00
7      33.50  1994-02-04   33.50
8      36.50  1994-02-07   33.50
9      35.75  1994-02-08   36.00
10     36.25  1994-02-09   35.75
11     36.50  1994-02-10   36.25
12     37.00  1994-02-11   36.25
13     37.00  1994-02-14   37.00
14     37.13  1994-02-15   36.75
15     36.75  1994-02-16   37.50
16     37.00  1994-02-17   37.25
17     36.25  1994-02-18   36.50
18     37.25  1994-02-22   36.25
19     37.25  1994-02-23   37.25
20     36.63  1994-02-24   37.00
21     36.00  1994-02-25   37.00
22     36.50  1994-02-28   36.25
23     36.25  1994-03-01   36.75
24     35.63  1994-03-02   35.25
25     35.75  1994-03-03   35.75
26     36.75  1994-03-04   36.00
27     37.88  1994-03-07   37.00
28     37.00  1994-03-08   38.00
29     37.50  1994-03-09   36.63
30     37.25  1994-03-10   37.25
31     37.25  1994-03-11   37.00
32     38.13  1994-03-14   38.50
33     37.63  1994-03-15   38.25
34     36.75  1994-03-16   37.50
35     36.50  1994-03-17   36.75
36     36.38  1994-03-18   36.75
37     35.50  1994-03-21   36.38
38     35.00  1994-03-22   35.25
39     35.13  1994-03-23   35.25
40     34.63  1994-03-24   35.13
41     32.75  1994-03-25   34.75
42     33.25  1994-03-28   33.00
43     32.75  1994-03-29   33.25
44     32.50  1994-03-30   32.50
45     33.25  1994-03-31   32.50
46     33.25  1994-04-04   32.25
47     33.50  1994-04-05   33.75
48     33.50  1994-04-06   34.00
49     33.38  1994-04-07   33.50
...      ...         ...     ...
5872  153.80  2017-05-23  154.90
5873  153.34  2017-05-24  153.84
5874  153.87  2017-05-25  153.73
5875  153.61  2017-05-26  154.00
5876  153.67  2017-05-30  153.42
5877  152.76  2017-05-31  153.97
5878  153.18  2017-06-01  153.17
5879  155.45  2017-06-02  153.58
5880  153.93  2017-06-05  154.34
5881  154.45  2017-06-06  153.90
5882  155.37  2017-06-07  155.02
5883  154.99  2017-06-08  155.25
5884  148.98  2017-06-09  155.19
5885  145.32  2017-06-12  145.74
5886  146.59  2017-06-13  147.16
5887  145.16  2017-06-14  147.50
5888  144.29  2017-06-15  143.32
5889  142.27  2017-06-16  143.78
5890  146.34  2017-06-19  143.66
5891  145.01  2017-06-20  146.87
5892  145.87  2017-06-21  145.52
5893  145.63  2017-06-22  145.77
5894  146.35  2017-06-23  145.13
5895  145.82  2017-06-26  147.17
5896  143.74  2017-06-27  145.01
5897  145.83  2017-06-28  144.49
5898  143.68  2017-06-29  144.71
5899  144.02  2017-06-30  144.45
5900  143.50  2017-07-03  144.88
5901  144.09  2017-07-05  143.69
5902  142.73  2017-07-06  143.02
5903  144.18  2017-07-07  142.90
5904  145.06  2017-07-10  144.11
5905  145.53  2017-07-11  144.73
5906  145.74  2017-07-12  145.87
5907  147.77  2017-07-13  145.50
5908  149.04  2017-07-14  147.97
5909  149.56  2017-07-17  148.82
5910  150.08  2017-07-18  149.20
5911  151.02  2017-07-19  150.48
5912  150.34  2017-07-20  151.50
5913  150.27  2017-07-21  149.99
5914  152.09  2017-07-24  150.58
5915  152.74  2017-07-25  151.80
5916  153.46  2017-07-26  153.35
5917  150.56  2017-07-27  153.75
5918  149.50  2017-07-28  149.89
5919  148.85  2017-07-31  149.90
5920  150.05  2017-08-01  149.10
5921  157.14  2017-08-02  159.28

[5922 rows x 3 columns]

In [28]:
AAPL_df = aapl_df[5479:]
AAPL_df = AAPL_df.reset_index()
del AAPL_df['index']
print(AAPL_df)

       close        date    open
0    120.530  2015-10-29  118.70
1    119.500  2015-10-30  120.99
2    121.180  2015-11-02  119.87
3    122.570  2015-11-03  120.79
4    122.000  2015-11-04  123.13
5    120.920  2015-11-05  121.85
6    121.060  2015-11-06  121.11
7    120.570  2015-11-09  120.96
8    116.770  2015-11-10  116.90
9    116.110  2015-11-11  116.37
10   115.720  2015-11-12  116.26
11   112.340  2015-11-13  115.20
12   114.175  2015-11-16  111.38
13   113.690  2015-11-17  114.92
14   117.290  2015-11-18  115.76
15   118.780  2015-11-19  117.64
16   119.300  2015-11-20  119.20
17   117.750  2015-11-23  119.27
18   118.880  2015-11-24  117.33
19   118.030  2015-11-25  119.21
20   117.810  2015-11-27  118.29
21   118.300  2015-11-30  117.99
22   117.340  2015-12-01  118.75
23   116.280  2015-12-02  117.05
24   115.200  2015-12-03  116.55
25   119.030  2015-12-04  115.29
26   118.280  2015-12-07  118.98
27   118.230  2015-12-08  117.52
28   115.620  2015-12-09  117.64
29   116.170  2015-12-10  116.04
30   113.180  2015-12-11  115.19
31   112.480  2015-12-14  112.18
32   110.490  2015-12-15  111.94
33   111.340  2015-12-16  111.07
34   108.980  2015-12-17  112.02
35   106.030  2015-12-18  108.91
36   107.330  2015-12-21  107.28
37   107.230  2015-12-22  107.40
38   108.610  2015-12-23  107.27
39   108.030  2015-12-24  109.00
40   106.820  2015-12-28  107.59
41   108.740  2015-12-29  106.96
42   107.320  2015-12-30  108.58
43   105.260  2015-12-31  107.01
44   105.350  2016-01-04  102.61
45   102.710  2016-01-05  105.75
46   100.700  2016-01-06  100.56
47    96.450  2016-01-07   98.68
48    96.960  2016-01-08   98.55
49    98.530  2016-01-11   98.97
..       ...         ...     ...
393  153.800  2017-05-23  154.90
394  153.340  2017-05-24  153.84
395  153.870  2017-05-25  153.73
396  153.610  2017-05-26  154.00
397  153.670  2017-05-30  153.42
398  152.760  2017-05-31  153.97
399  153.180  2017-06-01  153.17
400  155.450  2017-06-02  153.58
401  153.930  2017-06-05  154.34
402  154.450  2017-06-06  153.90
403  155.370  2017-06-07  155.02
404  154.990  2017-06-08  155.25
405  148.980  2017-06-09  155.19
406  145.320  2017-06-12  145.74
407  146.590  2017-06-13  147.16
408  145.160  2017-06-14  147.50
409  144.290  2017-06-15  143.32
410  142.270  2017-06-16  143.78
411  146.340  2017-06-19  143.66
412  145.010  2017-06-20  146.87
413  145.870  2017-06-21  145.52
414  145.630  2017-06-22  145.77
415  146.350  2017-06-23  145.13
416  145.820  2017-06-26  147.17
417  143.740  2017-06-27  145.01
418  145.830  2017-06-28  144.49
419  143.680  2017-06-29  144.71
420  144.020  2017-06-30  144.45
421  143.500  2017-07-03  144.88
422  144.090  2017-07-05  143.69
423  142.730  2017-07-06  143.02
424  144.180  2017-07-07  142.90
425  145.060  2017-07-10  144.11
426  145.530  2017-07-11  144.73
427  145.740  2017-07-12  145.87
428  147.770  2017-07-13  145.50
429  149.040  2017-07-14  147.97
430  149.560  2017-07-17  148.82
431  150.080  2017-07-18  149.20
432  151.020  2017-07-19  150.48
433  150.340  2017-07-20  151.50
434  150.270  2017-07-21  149.99
435  152.090  2017-07-24  150.58
436  152.740  2017-07-25  151.80
437  153.460  2017-07-26  153.35
438  150.560  2017-07-27  153.75
439  149.500  2017-07-28  149.89
440  148.850  2017-07-31  149.90
441  150.050  2017-08-01  149.10
442  157.140  2017-08-02  159.28

[443 rows x 3 columns]

In [11]:
#summary statistics on opening and closing prices for Apple stock
AAPL_df.describe()

            close        open
count  443.000000  443.000000
mean   117.780905  117.702376
std     18.846005   18.842831
min     90.340000   90.000000
25%    102.980000  102.630000
50%    112.880000  113.000000
75%    136.815000  136.755000
max    157.140000  159.280000

In [29]:
#reading in amazon data
with open("/Users/marshallringwood/Desktop/ECON213R/amzn.txt", "r") as h:
    amzn_df = json.load(h)
amzn_df

[{'close': 25.88, 'date': '1997-08-14', 'open': 26.13},
 {'close': 25.38, 'date': '1997-08-15', 'open': 23.5},
 {'close': 24.5, 'date': '1997-08-18', 'open': 24.38},
 {'close': 26.0, 'date': '1997-08-19', 'open': 25.13},
 {'close': 26.0, 'date': '1997-08-20', 'open': 25.0},
 {'close': 25.38, 'date': '1997-08-21', 'open': 25.63},
 {'close': 25.5, 'date': '1997-08-22', 'open': 25.25},
 {'close': 26.63, 'date': '1997-08-25', 'open': 25.25},
 {'close': 28.13, 'date': '1997-08-26', 'open': 26.88},
 {'close': 27.81, 'date': '1997-08-27', 'open': 27.69},
 {'close': 28.5, 'date': '1997-08-28', 'open': 27.63},
 {'close': 28.06, 'date': '1997-08-29', 'open': 28.38},
 {'close': 28.25, 'date': '1997-09-02', 'open': 28.13},
 {'close': 28.0, 'date': '1997-09-03', 'open': 28.13},
 {'close': 30.63, 'date': '1997-09-04', 'open': 28.38},
 {'close': 30.0, 'date': '1997-09-05', 'open': 31.0},
 {'close': 36.0, 'date': '1997-09-08', 'open': 30.38},
 {'close': 38.88, 'date': '1997-09-09', 'open': 37.75},
 {'close': 39.63, 'date': '1997-09-10', 'open': 39.75},
 {'close': 37.88, 'date': '1997-09-11', 'open': 38.88},
 {'close': 44.25, 'date': '1997-09-12', 'open': 38.25},
 {'close': 37.13, 'date': '1997-09-15', 'open': 42.38},
 {'close': 40.25, 'date': '1997-09-16', 'open': 38.75},
 {'close': 40.88, 'date': '1997-09-17', 'open': 41.5},
 {'close': 39.5, 'date': '1997-09-18', 'open': 41.25},
 {'close': 47.38, 'date': '1997-09-19', 'open': 41.63},
 {'close': 54.0, 'date': '1997-09-22', 'open': 48.63},
 {'close': 55.5, 'date': '1997-09-23', 'open': 53.88},
 {'close': 52.5, 'date': '1997-09-24', 'open': 55.75},
 {'close': 49.0, 'date': '1997-09-25', 'open': 49.5},
 {'close': 50.0, 'date': '1997-09-26', 'open': 50.88},
 {'close': 48.5, 'date': '1997-09-29', 'open': 49.75},
 {'close': 52.13, 'date': '1997-09-30', 'open': 48.0},
 {'close': 48.25, 'date': '1997-10-01', 'open': 51.38},
 {'close': 48.13, 'date': '1997-10-02', 'open': 48.5},
 {'close': 48.25, 'date': '1997-10-03', 'open': 49.0},
 {'close': 49.5, 'date': '1997-10-06', 'open': 48.0},
 {'close': 48.75, 'date': '1997-10-07', 'open': 49.0},
 {'close': 48.13, 'date': '1997-10-08', 'open': 49.75},
 {'close': 45.0, 'date': '1997-10-09', 'open': 48.0},
 {'close': 46.88, 'date': '1997-10-10', 'open': 45.0},
 {'close': 48.0, 'date': '1997-10-13', 'open': 48.0},
 {'close': 47.75, 'date': '1997-10-14', 'open': 48.75},
 {'close': 47.13, 'date': '1997-10-15', 'open': 47.0},
 {'close': 43.5, 'date': '1997-10-16', 'open': 46.88},
 {'close': 43.5, 'date': '1997-10-17', 'open': 43.38},
 {'close': 45.88, 'date': '1997-10-20', 'open': 46.0},
 {'close': 53.13, 'date': '1997-10-21', 'open': 47.5},
 {'close': 54.25, 'date': '1997-10-22', 'open': 53.0},
 {'close': 54.0, 'date': '1997-10-23', 'open': 52.25},
 {'close': 60.38, 'date': '1997-10-24', 'open': 57.0},
 {'close': 51.25, 'date': '1997-10-27', 'open': 57.63},
 {'close': 59.38, 'date': '1997-10-28', 'open': 47.0},
 {'close': 64.75, 'date': '1997-10-29', 'open': 61.75},
 {'close': 61.5, 'date': '1997-10-30', 'open': 62.5},
 {'close': 61.0, 'date': '1997-10-31', 'open': 64.25},
 {'close': 60.88, 'date': '1997-11-03', 'open': 61.38},
 {'close': 59.5, 'date': '1997-11-04', 'open': 59.0},
 {'close': 58.5, 'date': '1997-11-05', 'open': 59.75},
 {'close': 55.94, 'date': '1997-11-06', 'open': 59.0},
 {'close': 53.75, 'date': '1997-11-07', 'open': 53.0},
 {'close': 50.5, 'date': '1997-11-10', 'open': 54.0},
 {'close': 47.38, 'date': '1997-11-11', 'open': 50.94},
 {'close': 45.25, 'date': '1997-11-12', 'open': 45.31},
 {'close': 46.31, 'date': '1997-11-13', 'open': 47.38},
 {'close': 50.0, 'date': '1997-11-14', 'open': 47.25},
 {'close': 52.5, 'date': '1997-11-17', 'open': 50.75},
 {'close': 53.0, 'date': '1997-11-18', 'open': 52.5},
 {'close': 54.13, 'date': '1997-11-19', 'open': 52.88},
 {'close': 55.0, 'date': '1997-11-20', 'open': 54.88},
 {'close': 53.88, 'date': '1997-11-21', 'open': 54.63},
 {'close': 50.75, 'date': '1997-11-24', 'open': 52.5},
 {'close': 50.44, 'date': '1997-11-25', 'open': 50.88},
 {'close': 51.13, 'date': '1997-11-26', 'open': 50.88},
 {'close': 49.5, 'date': '1997-11-28', 'open': 51.25},
 {'close': 51.25, 'date': '1997-12-01', 'open': 50.88},
 {'close': 50.81, 'date': '1997-12-02', 'open': 51.13},
 {'close': 52.38, 'date': '1997-12-03', 'open': 50.38},
 {'close': 54.0, 'date': '1997-12-04', 'open': 52.81},
 {'close': 55.13, 'date': '1997-12-05', 'open': 53.25},
 {'close': 56.5, 'date': '1997-12-08', 'open': 54.5},
 {'close': 56.25, 'date': '1997-12-09', 'open': 56.0},
 {'close': 54.13, 'date': '1997-12-10', 'open': 55.0},
 {'close': 56.25, 'date': '1997-12-11', 'open': 52.75},
 {'close': 54.5, 'date': '1997-12-12', 'open': 55.75},
 {'close': 55.0, 'date': '1997-12-15', 'open': 55.0},
 {'close': 53.5, 'date': '1997-12-16', 'open': 55.75},
 {'close': 52.69, 'date': '1997-12-17', 'open': 52.5},
 {'close': 51.5, 'date': '1997-12-18', 'open': 52.25},
 {'close': 54.0, 'date': '1997-12-19', 'open': 50.75},
 {'close': 56.38, 'date': '1997-12-22', 'open': 54.0},
 {'close': 55.5, 'date': '1997-12-23', 'open': 56.25},
 {'close': 55.25, 'date': '1997-12-24', 'open': 55.5},
 {'close': 54.25, 'date': '1997-12-26', 'open': 54.75},
 {'close': 57.0, 'date': '1997-12-29', 'open': 55.0},
 {'close': 58.19, 'date': '1997-12-30', 'open': 58.0},
 {'close': 60.25, 'date': '1997-12-31', 'open': 58.5},
 {'close': 59.5, 'date': '1998-01-02', 'open': 60.0},
 {'close': 57.0, 'date': '1998-01-05', 'open': 58.63},
 {'close': 58.06, 'date': '1998-01-06', 'open': 56.38},
 {'close': 57.38, 'date': '1998-01-07', 'open': 58.0},
 {'close': 55.38, 'date': '1998-01-08', 'open': 56.38},
 {'close': 51.13, 'date': '1998-01-09', 'open': 56.0},
 {'close': 51.63, 'date': '1998-01-12', 'open': 50.0},
 {'close': 55.75, 'date': '1998-01-13', 'open': 52.13},
 {'close': 58.5, 'date': '1998-01-14', 'open': 55.88},
 {'close': 59.44, 'date': '1998-01-15', 'open': 57.5},
 {'close': 57.5, 'date': '1998-01-16', 'open': 59.5},
 {'close': 59.44, 'date': '1998-01-20', 'open': 57.88},
 {'close': 60.88, 'date': '1998-01-21', 'open': 59.25},
 {'close': 61.63, 'date': '1998-01-22', 'open': 60.88},
 {'close': 59.25, 'date': '1998-01-23', 'open': 64.13},
 {'close': 57.75, 'date': '1998-01-26', 'open': 59.75},
 {'close': 57.0, 'date': '1998-01-27', 'open': 57.81},
 {'close': 57.25, 'date': '1998-01-28', 'open': 57.0},
 {'close': 59.5, 'date': '1998-01-29', 'open': 57.5},
 {'close': 59.0, 'date': '1998-01-30', 'open': 60.0},
 {'close': 62.38, 'date': '1998-02-02', 'open': 59.38},
 {'close': 61.81, 'date': '1998-02-03', 'open': 62.25},
 {'close': 60.75, 'date': '1998-02-04', 'open': 60.75},
 {'close': 59.25, 'date': '1998-02-05', 'open': 61.38},
 {'close': 58.88, 'date': '1998-02-06', 'open': 59.13},
 {'close': 58.25, 'date': '1998-02-09', 'open': 59.0},
 {'close': 63.63, 'date': '1998-02-10', 'open': 58.5},
 {'close': 63.5, 'date': '1998-02-11', 'open': 63.5},
 {'close': 63.13, 'date': '1998-02-12', 'open': 63.25},
 {'close': 62.25, 'date': '1998-02-13', 'open': 63.0},
 {'close': 61.75, 'date': '1998-02-17', 'open': 62.63},
 {'close': 60.88, 'date': '1998-02-18', 'open': 61.75},
 {'close': 62.75, 'date': '1998-02-19', 'open': 61.31},
 {'close': 63.25, 'date': '1998-02-20', 'open': 62.75},
 {'close': 64.88, 'date': '1998-02-23', 'open': 63.5},
 {'close': 64.88, 'date': '1998-02-24', 'open': 65.0},
 {'close': 65.88, 'date': '1998-02-25', 'open': 65.63},
 {'close': 72.75, 'date': '1998-02-26', 'open': 65.56},
 {'close': 77.0, 'date': '1998-02-27', 'open': 72.25},
 {'close': 76.25, 'date': '1998-03-02', 'open': 75.88},
 {'close': 71.75, 'date': '1998-03-03', 'open': 75.5},
 {'close': 73.44, 'date': '1998-03-04', 'open': 72.0},
 {'close': 75.0, 'date': '1998-03-05', 'open': 71.75},
 {'close': 76.75, 'date': '1998-03-06', 'open': 75.63},
 {'close': 83.5, 'date': '1998-03-09', 'open': 76.88},
 {'close': 83.11, 'date': '1998-03-10', 'open': 85.5},
 {'close': 79.63, 'date': '1998-03-11', 'open': 82.0},
 {'close': 78.5, 'date': '1998-03-12', 'open': 78.75},
 {'close': 78.69, 'date': '1998-03-13', 'open': 79.63},
 {'close': 79.0, 'date': '1998-03-16', 'open': 79.56},
 {'close': 79.88, 'date': '1998-03-17', 'open': 79.75},
 {'close': 85.31, 'date': '1998-03-18', 'open': 79.25},
 {'close': 84.0, 'date': '1998-03-19', 'open': 85.38},
 {'close': 84.0, 'date': '1998-03-20', 'open': 84.0},
 {'close': 83.81, 'date': '1998-03-23', 'open': 83.56},
 {'close': 84.25, 'date': '1998-03-24', 'open': 82.5},
 {'close': 81.69, 'date': '1998-03-25', 'open': 85.0},
 {'close': 82.75, 'date': '1998-03-26', 'open': 81.75},
 {'close': 85.0, 'date': '1998-03-27', 'open': 84.25},
 {'close': 85.88, 'date': '1998-03-30', 'open': 85.88},
 {'close': 85.53, 'date': '1998-03-31', 'open': 85.38},
 {'close': 90.13, 'date': '1998-04-01', 'open': 85.25},
 {'close': 95.06, 'date': '1998-04-02', 'open': 91.13},
 {'close': 93.0, 'date': '1998-04-03', 'open': 96.25},
 {'close': 88.63, 'date': '1998-04-06', 'open': 94.25},
 {'close': 86.0, 'date': '1998-04-07', 'open': 87.0},
 {'close': 88.63, 'date': '1998-04-08', 'open': 86.38},
 {'close': 95.25, 'date': '1998-04-09', 'open': 92.38},
 {'close': 94.31, 'date': '1998-04-13', 'open': 94.88},
 {'close': 97.19, 'date': '1998-04-14', 'open': 93.88},
 {'close': 96.13, 'date': '1998-04-15', 'open': 98.0},
 {'close': 98.5, 'date': '1998-04-16', 'open': 96.13},
 {'close': 94.88, 'date': '1998-04-17', 'open': 95.81},
 {'close': 94.25, 'date': '1998-04-20', 'open': 95.38},
 {'close': 93.06, 'date': '1998-04-21', 'open': 93.06},
 {'close': 87.25, 'date': '1998-04-22', 'open': 87.25},
 {'close': 81.0, 'date': '1998-04-23', 'open': 87.0},
 {'close': 84.88, 'date': '1998-04-24', 'open': 82.0},
 {'close': 82.75, 'date': '1998-04-27', 'open': 83.38},
 {'close': 95.63, 'date': '1998-04-28', 'open': 92.88},
 {'close': 95.5, 'date': '1998-04-29', 'open': 97.25},
 {'close': 91.75, 'date': '1998-04-30', 'open': 97.5},
 {'close': 94.5, 'date': '1998-05-01', 'open': 92.75},
 {'close': 95.25, 'date': '1998-05-04', 'open': 95.0},
 {'close': 93.72, 'date': '1998-05-05', 'open': 94.0},
 {'close': 90.38, 'date': '1998-05-06', 'open': 94.0},
 {'close': 91.0, 'date': '1998-05-07', 'open': 91.0},
 {'close': 92.38, 'date': '1998-05-08', 'open': 91.25},
 {'close': 86.88, 'date': '1998-05-11', 'open': 92.94},
 {'close': 91.38, 'date': '1998-05-12', 'open': 87.75},
 {'close': 92.88, 'date': '1998-05-13', 'open': 90.5},
 {'close': 91.56, 'date': '1998-05-14', 'open': 92.0},
 {'close': 89.63, 'date': '1998-05-15', 'open': 91.88},
 {'close': 88.06, 'date': '1998-05-18', 'open': 90.0},
 {'close': 90.38, 'date': '1998-05-19', 'open': 89.63},
 {'close': 88.63, 'date': '1998-05-20', 'open': 90.38},
 {'close': 88.75, 'date': '1998-05-21', 'open': 89.5},
 {'close': 86.0, 'date': '1998-05-22', 'open': 88.38},
 {'close': 81.88, 'date': '1998-05-26', 'open': 86.06},
 {'close': 86.63, 'date': '1998-05-27', 'open': 80.38},
 {'close': 85.94, 'date': '1998-05-28', 'open': 87.25},
 {'close': 88.13, 'date': '1998-05-29', 'open': 85.88},
 {'close': 85.63, 'date': '1998-06-01', 'open': 88.0},
 {'close': 43.69, 'date': '1998-06-02', 'open': 43.63},
 {'close': 42.25, 'date': '1998-06-03', 'open': 44.88},
 {'close': 43.88, 'date': '1998-06-04', 'open': 42.94},
 {'close': 44.25, 'date': '1998-06-05', 'open': 43.75},
 {'close': 46.25, 'date': '1998-06-08', 'open': 43.81},
 {'close': 51.25, 'date': '1998-06-09', 'open': 46.44},
 {'close': 54.12, 'date': '1998-06-10', 'open': 51.63},
 {'close': 62.5, 'date': '1998-06-11', 'open': 55.25},
 {'close': 61.0, 'date': '1998-06-12', 'open': 63.5},
 {'close': 65.75, 'date': '1998-06-15', 'open': 59.5},
 {'close': 73.63, 'date': '1998-06-16', 'open': 66.75},
 {'close': 79.0, 'date': '1998-06-17', 'open': 75.88},
 {'close': 72.13, 'date': '1998-06-18', 'open': 81.0},
 {'close': 75.81, 'date': '1998-06-19', 'open': 71.06},
 {'close': 81.38, 'date': '1998-06-22', 'open': 74.75},
 {'close': 92.69, 'date': '1998-06-23', 'open': 81.06},
 {'close': 99.81, 'date': '1998-06-24', 'open': 95.0},
 {'close': 99.06, 'date': '1998-06-25', 'open': 100.0},
 {'close': 94.25, 'date': '1998-06-26', 'open': 97.5},
 {'close': 98.75, 'date': '1998-06-29', 'open': 94.75},
 {'close': 99.75, 'date': '1998-06-30', 'open': 97.81},
 {'close': 114.1, 'date': '1998-07-01', 'open': 101.8},
 {'close': 124.0, 'date': '1998-07-02', 'open': 115.8},
 {'close': 139.5, 'date': '1998-07-06', 'open': 127.4},
 {'close': 122.1, 'date': '1998-07-07', 'open': 143.0},
 {'close': 111.6, 'date': '1998-07-08', 'open': 111.9},
 {'close': 105.5, 'date': '1998-07-09', 'open': 110.6},
 {'close': 99.5, 'date': '1998-07-10', 'open': 103.0},
 {'close': 107.6, 'date': '1998-07-13', 'open': 96.5},
 {'close': 115.0, 'date': '1998-07-14', 'open': 108.5},
 {'close': 112.5, 'date': '1998-07-15', 'open': 116.0},
 {'close': 113.37, 'date': '1998-07-16', 'open': 113.44},
 {'close': 119.8, 'date': '1998-07-17', 'open': 112.4},
 {'close': 137.5, 'date': '1998-07-20', 'open': 121.1},
 {'close': 132.1, 'date': '1998-07-21', 'open': 137.3},
 {'close': 134.0, 'date': '1998-07-22', 'open': 134.0},
 {'close': 127.6, 'date': '1998-07-23', 'open': 130.0},
 {'close': 124.3, 'date': '1998-07-24', 'open': 129.3},
 {'close': 125.6, 'date': '1998-07-27', 'open': 119.1},
 {'close': 118.9, 'date': '1998-07-28', 'open': 124.4},
 {'close': 107.8, 'date': '1998-07-29', 'open': 120.5},
 {'close': 113.8, 'date': '1998-07-30', 'open': 111.8},
 {'close': 110.9, 'date': '1998-07-31', 'open': 114.5},
 {'close': 108.3, 'date': '1998-08-03', 'open': 109.8},
 {'close': 109.9, 'date': '1998-08-04', 'open': 110.1},
 {'close': 106.2, 'date': '1998-08-05', 'open': 112.8},
 {'close': 109.5, 'date': '1998-08-06', 'open': 104.4},
 {'close': 116.0, 'date': '1998-08-07', 'open': 111.3},
 {'close': 121.6, 'date': '1998-08-10', 'open': 117.0},
 {'close': 124.0, 'date': '1998-08-11', 'open': 115.5},
 {'close': 130.4, 'date': '1998-08-12', 'open': 126.8},
 {'close': 127.5, 'date': '1998-08-13', 'open': 130.6},
 {'close': 122.8, 'date': '1998-08-14', 'open': 130.7},
 {'close': 119.7, 'date': '1998-08-17', 'open': 120.8},
 {'close': 128.7, 'date': '1998-08-18', 'open': 121.2},
 {'close': 128.8, 'date': '1998-08-19', 'open': 131.3},
 {'close': 129.1, 'date': '1998-08-20', 'open': 126.3},
 {'close': 129.7, 'date': '1998-08-21', 'open': 127.3},
 {'close': 134.8, 'date': '1998-08-24', 'open': 130.3},
 {'close': 131.6, 'date': '1998-08-25', 'open': 137.4},
 {'close': 127.3, 'date': '1998-08-26', 'open': 129.8},
 {'close': 119.0, 'date': '1998-08-27', 'open': 124.4},
 {'close': 105.9, 'date': '1998-08-28', 'open': 119.8},
 {'close': 83.75, 'date': '1998-08-31', 'open': 105.4},
 {'close': 79.95, 'date': '1998-09-01', 'open': 76.13},
 {'close': 87.88, 'date': '1998-09-02', 'open': 83.13},
 {'close': 85.88, 'date': '1998-09-03', 'open': 83.63},
 {'close': 86.25, 'date': '1998-09-04', 'open': 86.69},
 {'close': 92.25, 'date': '1998-09-08', 'open': 94.0},
 {'close': 84.5, 'date': '1998-09-09', 'open': 89.5},
 {'close': 79.63, 'date': '1998-09-10', 'open': 79.38},
 {'close': 76.06, 'date': '1998-09-11', 'open': 78.38},
 {'close': 73.69, 'date': '1998-09-14', 'open': 80.38},
 {'close': 73.0, 'date': '1998-09-15', 'open': 70.81},
 {'close': 84.5, 'date': '1998-09-16', 'open': 74.25},
 {'close': 77.0, 'date': '1998-09-17', 'open': 80.44},
 {'close': 79.69, 'date': '1998-09-18', 'open': 77.75},
 {'close': 85.5, 'date': '1998-09-21', 'open': 76.0},
 {'close': 88.19, 'date': '1998-09-22', 'open': 88.25},
 {'close': 105.1, 'date': '1998-09-23', 'open': 90.81},
 {'close': 102.1, 'date': '1998-09-24', 'open': 107.1},
 {'close': 109.3, 'date': '1998-09-25', 'open': 98.5},
 {'close': 115.6, 'date': '1998-09-28', 'open': 116.4},
 {'close': 113.1, 'date': '1998-09-29', 'open': 117.3},
 {'close': 111.6, 'date': '1998-09-30', 'open': 111.5},
 {'close': 102.6, 'date': '1998-10-01', 'open': 108.0},
 {'close': 110.3, 'date': '1998-10-02', 'open': 105.3},
 {'close': 104.7, 'date': '1998-10-05', 'open': 108.9},
 {'close': 108.3, 'date': '1998-10-06', 'open': 111.5},
 {'close': 93.44, 'date': '1998-10-07', 'open': 102.6},
 {'close': 86.19, 'date': '1998-10-08', 'open': 82.88},
 {'close': 91.19, 'date': '1998-10-09', 'open': 90.25},
 {'close': 93.19, 'date': '1998-10-12', 'open': 97.13},
 {'close': 91.38, 'date': '1998-10-13', 'open': 91.81},
 {'close': 93.5, 'date': '1998-10-14', 'open': 91.06},
 {'close': 97.06, 'date': '1998-10-15', 'open': 94.25},
 {'close': 99.44, 'date': '1998-10-16', 'open': 98.63},
 {'close': 105.8, 'date': '1998-10-19', 'open': 99.0},
 {'close': 106.8, 'date': '1998-10-20', 'open': 108.8},
 {'close': 110.0, 'date': '1998-10-21', 'open': 109.4},
 {'close': 114.7, 'date': '1998-10-22', 'open': 107.6},
 {'close': 116.1, 'date': '1998-10-23', 'open': 114.5},
 {'close': 121.4, 'date': '1998-10-26', 'open': 119.1},
 {'close': 116.3, 'date': '1998-10-27', 'open': 124.1},
 {'close': 117.1, 'date': '1998-10-28', 'open': 116.9},
 {'close': 126.5, 'date': '1998-10-29', 'open': 121.3},
 {'close': 126.4, 'date': '1998-10-30', 'open': 126.6},
 {'close': 131.0, 'date': '1998-11-02', 'open': 128.1},
 {'close': 126.1, 'date': '1998-11-03', 'open': 131.1},
 {'close': 129.8, 'date': '1998-11-04', 'open': 131.4},
 {'close': 128.5, 'date': '1998-11-05', 'open': 127.7},
 {'close': 124.6, 'date': '1998-11-06', 'open': 126.0},
 {'close': 126.9, 'date': '1998-11-09', 'open': 121.9},
 {'close': 131.8, 'date': '1998-11-10', 'open': 128.3},
 {'close': 126.6, 'date': '1998-11-11', 'open': 133.6},
 {'close': 131.0, 'date': '1998-11-12', 'open': 125.5},
 {'close': 127.8, 'date': '1998-11-13', 'open': 131.9},
 {'close': 126.3, 'date': '1998-11-16', 'open': 128.5},
 {'close': 148.5, 'date': '1998-11-17', 'open': 129.4},
 {'close': 164.0, 'date': '1998-11-18', 'open': 151.6},
 {'close': 153.3, 'date': '1998-11-19', 'open': 171.0},
 {'close': 180.6, 'date': '1998-11-20', 'open': 175.0},
 {'close': 218.0, 'date': '1998-11-23', 'open': 190.9},
 {'close': 214.5, 'date': '1998-11-24', 'open': 224.0},
 {'close': 210.31, 'date': '1998-11-25', 'open': 216.5},
 {'close': 216.6, 'date': '1998-11-27', 'open': 217.3},
 {'close': 192.0, 'date': '1998-11-30', 'open': 219.6},
 {'close': 209.5, 'date': '1998-12-01', 'open': 185.5},
 {'close': 199.5, 'date': '1998-12-02', 'open': 206.9},
 {'close': 189.5, 'date': '1998-12-03', 'open': 199.1},
 {'close': 188.5, 'date': '1998-12-04', 'open': 195.5},
 {'close': 191.0, 'date': '1998-12-07', 'open': 193.0},
 {'close': 204.1, 'date': '1998-12-08', 'open': 189.6},
 {'close': 216.3, 'date': '1998-12-09', 'open': 205.4},
 {'close': 213.1, 'date': '1998-12-10', 'open': 217.6},
 {'close': 223.0, 'date': '1998-12-11', 'open': 210.1},
 {'close': 222.3, 'date': '1998-12-14', 'open': 221.1},
 {'close': 242.8, 'date': '1998-12-15', 'open': 227.0},
 {'close': 289.0, 'date': '1998-12-16', 'open': 259.1},
 {'close': 276.8, 'date': '1998-12-17', 'open': 264.0},
 {'close': 286.7, 'date': '1998-12-18', 'open': 283.0},
 {'close': 318.8, 'date': '1998-12-21', 'open': 303.5},
 {'close': 322.4, 'date': '1998-12-22', 'open': 326.9},
 {'close': 325.0, 'date': '1998-12-23', 'open': 328.0},
 {'close': 324.8, 'date': '1998-12-24', 'open': 322.3},
 {'close': 351.9, 'date': '1998-12-28', 'open': 331.0},
 {'close': 332.3, 'date': '1998-12-29', 'open': 350.0},
 {'close': 321.3, 'date': '1998-12-30', 'open': 333.0},
 {'close': 321.3, 'date': '1998-12-31', 'open': 317.3},
 {'close': 354.9, 'date': '1999-01-04', 'open': 327.7},
 {'close': 124.6, 'date': '1999-01-05', 'open': 109.1},
 {'close': 138.0, 'date': '1999-01-06', 'open': 136.5},
 {'close': 158.9, 'date': '1999-01-07', 'open': 137.1},
 {'close': 160.3, 'date': '1999-01-08', 'open': 185.0},
 {'close': 184.6, 'date': '1999-01-11', 'open': 184.0},
 {'close': 163.4, 'date': '1999-01-12', 'open': 180.5},
 {'close': 148.0, 'date': '1999-01-13', 'open': 129.0},
 {'close': 138.0, 'date': '1999-01-14', 'open': 150.0},
 {'close': 140.4, 'date': '1999-01-15', 'open': 140.0},

In [30]:
#creating amazon data frame
amzn_df = pd.DataFrame.from_dict(amzn_df, orient='columns')
AMZN_df = amzn_df[4582:]
AMAZN_df = AMZN_df[:443]
AMAZN_df = AMAZN_df.reset_index()
del AMAZN_df['index']
AMAZN_df

        close        date     open
0     626.550  2015-10-29   617.70
1     625.900  2015-10-30   626.01
2     628.350  2015-11-02   627.13
3     625.310  2015-11-03   629.53
4     640.950  2015-11-04   627.76
5     655.650  2015-11-05   647.10
6     659.370  2015-11-06   655.00
7     655.490  2015-11-09   658.65
8     659.680  2015-11-10   651.01
9     673.250  2015-11-11   663.25
10    665.600  2015-11-12   673.00
11    642.350  2015-11-13   663.57
12    647.810  2015-11-16   640.92
13    643.300  2015-11-17   650.65
14    663.540  2015-11-18   646.51
15    661.270  2015-11-19   664.99
16    668.450  2015-11-20   667.94
17    678.990  2015-11-23   671.50
18    671.150  2015-11-24   674.14
19    675.340  2015-11-25   675.00
20    673.260  2015-11-27   680.80
21    664.800  2015-11-30   675.90
22    679.060  2015-12-01   673.75
23    676.010  2015-12-02   681.00
24    666.250  2015-12-03   679.44
25    672.640  2015-12-04   666.00
26    669.830  2015-12-07   674.74
27    677.330  2015-12-08   663.13
28    664.790  2015-12-09   678.00
29    662.320  2015-12-10   665.59
30    640.150  2015-12-11   651.23
31    657.910  2015-12-14   641.75
32    658.640  2015-12-15   665.03
33    675.770  2015-12-16   663.56
34    670.650  2015-12-17   680.00
35    664.140  2015-12-18   668.65
36    664.510  2015-12-21   668.50
37    663.150  2015-12-22   666.83
38    663.700  2015-12-23   666.50
39    662.790  2015-12-24   663.35
40    675.200  2015-12-28   665.56
41    693.970  2015-12-29   677.98
42    689.070  2015-12-30   691.89
43    675.890  2015-12-31   686.08
44    636.990  2016-01-04   656.29
45    633.790  2016-01-05   646.86
46    632.650  2016-01-06   622.00
47    607.940  2016-01-07   621.80
48    607.050  2016-01-08   619.66
49    617.740  2016-01-11   612.48
..        ...         ...      ...
393   971.540  2017-05-23   975.02
394   980.350  2017-05-24   976.00
395   993.380  2017-05-25   984.85
396   995.780  2017-05-26   995.00
397   996.700  2017-05-30   996.51
398   994.620  2017-05-31  1000.00
399   995.950  2017-06-01   998.59
400  1006.730  2017-06-02   998.99
401  1011.340  2017-06-05  1007.23
402  1002.970  2017-06-06  1012.00
403  1010.070  2017-06-07  1005.95
404  1009.940  2017-06-08  1012.06
405   978.310  2017-06-09  1012.50
406   964.830  2017-06-12   967.00
407   980.790  2017-06-13   977.99
408   976.470  2017-06-14   988.59
409   964.170  2017-06-15   958.70
410   987.710  2017-06-16   996.00
411   995.170  2017-06-19  1017.00
412   992.590  2017-06-20   998.00
413  1002.230  2017-06-21   998.70
414  1001.300  2017-06-22  1002.23
415  1003.740  2017-06-23  1002.54
416   993.980  2017-06-26  1008.50
417   976.780  2017-06-27   990.69
418   990.330  2017-06-28   978.55
419   975.930  2017-06-29   979.00
420   968.000  2017-06-30   980.12
421   953.660  2017-07-03   972.79
422   971.400  2017-07-05   961.53
423   965.140  2017-07-06   964.66
424   978.760  2017-07-07   969.55
425   996.470  2017-07-10   985.00
426   994.130  2017-07-11   993.00
427  1006.510  2017-07-12  1000.65
428   999.855  2017-07-13  1004.62
429  1001.810  2017-07-14  1002.40
430  1010.040  2017-07-17  1004.69
431  1024.380  2017-07-18  1006.00
432  1026.870  2017-07-19  1025.00
433  1028.700  2017-07-20  1031.59
434  1025.670  2017-07-21  1021.28
435  1038.950  2017-07-24  1028.34
436  1039.870  2017-07-25  1038.05
437  1052.800  2017-07-26  1043.20
438  1046.000  2017-07-27  1069.55
439  1020.040  2017-07-28  1012.14
440   987.780  2017-07-31  1019.05
441   996.190  2017-08-01   996.11
442   995.890  2017-08-02  1001.77

[443 rows x 3 columns]

In [31]:
with open("/Users/marshallringwood/Desktop/ECON213R/goog.txt", "r") as i:
    goog_df = json.load(i)
goog_df

[{'close': 716.92, 'date': '2015-10-29', 'open': 710.5},
 {'close': 710.81, 'date': '2015-10-30', 'open': 715.73},
 {'close': 721.11, 'date': '2015-11-02', 'open': 711.06},
 {'close': 722.16, 'date': '2015-11-03', 'open': 718.86},
 {'close': 728.11, 'date': '2015-11-04', 'open': 722.0},
 {'close': 731.25, 'date': '2015-11-05', 'open': 729.47},
 {'close': 733.76, 'date': '2015-11-06', 'open': 731.5},
 {'close': 724.89, 'date': '2015-11-09', 'open': 730.2},
 {'close': 728.32, 'date': '2015-11-10', 'open': 724.4},
 {'close': 735.4, 'date': '2015-11-11', 'open': 732.46},
 {'close': 731.23, 'date': '2015-11-12', 'open': 731.0},
 {'close': 717.0, 'date': '2015-11-13', 'open': 729.17},
 {'close': 728.96, 'date': '2015-11-16', 'open': 715.6},
 {'close': 725.3, 'date': '2015-11-17', 'open': 729.29},
 {'close': 740.0, 'date': '2015-11-18', 'open': 727.58},
 {'close': 738.41, 'date': '2015-11-19', 'open': 738.74},
 {'close': 756.6, 'date': '2015-11-20', 'open': 746.53},
 {'close': 755.98, 'date': '2015-11-23', 'open': 757.45},
 {'close': 748.28, 'date': '2015-11-24', 'open': 752.0},
 {'close': 748.15, 'date': '2015-11-25', 'open': 748.14},
 {'close': 750.26, 'date': '2015-11-27', 'open': 748.46},
 {'close': 742.6, 'date': '2015-11-30', 'open': 748.81},
 {'close': 767.04, 'date': '2015-12-01', 'open': 747.11},
 {'close': 762.38, 'date': '2015-12-02', 'open': 768.9},
 {'close': 752.54, 'date': '2015-12-03', 'open': 766.01},
 {'close': 766.81, 'date': '2015-12-04', 'open': 753.1},
 {'close': 763.25, 'date': '2015-12-07', 'open': 767.77},
 {'close': 762.37, 'date': '2015-12-08', 'open': 757.89},
 {'close': 751.61, 'date': '2015-12-09', 'open': 759.17},
 {'close': 749.46, 'date': '2015-12-10', 'open': 752.85},
 {'close': 738.87, 'date': '2015-12-11', 'open': 741.16},
 {'close': 747.77, 'date': '2015-12-14', 'open': 741.79},
 {'close': 743.4, 'date': '2015-12-15', 'open': 753.0},
 {'close': 758.09, 'date': '2015-12-16', 'open': 750.0},
 {'close': 749.43, 'date': '2015-12-17', 'open': 762.42},
 {'close': 739.31, 'date': '2015-12-18', 'open': 746.51},
 {'close': 747.77, 'date': '2015-12-21', 'open': 746.13},
 {'close': 750.0, 'date': '2015-12-22', 'open': 751.65},
 {'close': 750.31, 'date': '2015-12-23', 'open': 753.47},
 {'close': 748.4, 'date': '2015-12-24', 'open': 749.55},
 {'close': 762.51, 'date': '2015-12-28', 'open': 752.92},
 {'close': 776.6, 'date': '2015-12-29', 'open': 766.69},
 {'close': 771.0, 'date': '2015-12-30', 'open': 776.6},
 {'close': 758.88, 'date': '2015-12-31', 'open': 769.5},
 {'close': 741.84, 'date': '2016-01-04', 'open': 743.0},
 {'close': 742.58, 'date': '2016-01-05', 'open': 746.45},
 {'close': 743.62, 'date': '2016-01-06', 'open': 730.0},
 {'close': 726.39, 'date': '2016-01-07', 'open': 730.31},
 {'close': 714.47, 'date': '2016-01-08', 'open': 731.45},
 {'close': 716.03, 'date': '2016-01-11', 'open': 716.61},
 {'close': 726.07, 'date': '2016-01-12', 'open': 721.68},
 {'close': 700.56, 'date': '2016-01-13', 'open': 730.85},
 {'close': 714.72, 'date': '2016-01-14', 'open': 705.38},
 {'close': 694.45, 'date': '2016-01-15', 'open': 692.29},
 {'close': 701.79, 'date': '2016-01-19', 'open': 703.3},
 {'close': 698.45, 'date': '2016-01-20', 'open': 688.61},
 {'close': 706.59, 'date': '2016-01-21', 'open': 702.18},
 {'close': 725.25, 'date': '2016-01-22', 'open': 723.6},
 {'close': 711.67, 'date': '2016-01-25', 'open': 723.58},
 {'close': 713.04, 'date': '2016-01-26', 'open': 713.85},
 {'close': 699.99, 'date': '2016-01-27', 'open': 713.67},
 {'close': 730.96, 'date': '2016-01-28', 'open': 722.22},
 {'close': 742.95, 'date': '2016-01-29', 'open': 731.53},
 {'close': 752.0, 'date': '2016-02-01', 'open': 750.46},
 {'close': 764.65, 'date': '2016-02-02', 'open': 784.5},
 {'close': 726.95, 'date': '2016-02-03', 'open': 770.22},
 {'close': 708.01, 'date': '2016-02-04', 'open': 722.81},
 {'close': 683.57, 'date': '2016-02-05', 'open': 703.87},
 {'close': 682.74, 'date': '2016-02-08', 'open': 667.85},
 {'close': 678.11, 'date': '2016-02-09', 'open': 672.32},
 {'close': 684.12, 'date': '2016-02-10', 'open': 686.86},
 {'close': 683.11, 'date': '2016-02-11', 'open': 675.0},
 {'close': 682.4, 'date': '2016-02-12', 'open': 690.26},
 {'close': 691.0, 'date': '2016-02-16', 'open': 692.98},
 {'close': 708.4, 'date': '2016-02-17', 'open': 699.0},
 {'close': 697.35, 'date': '2016-02-18', 'open': 710.0},
 {'close': 700.91, 'date': '2016-02-19', 'open': 695.03},
 {'close': 706.46, 'date': '2016-02-22', 'open': 707.45},
 {'close': 695.85, 'date': '2016-02-23', 'open': 701.45},
 {'close': 699.56, 'date': '2016-02-24', 'open': 688.92},
 {'close': 705.75, 'date': '2016-02-25', 'open': 700.01},
 {'close': 705.07, 'date': '2016-02-26', 'open': 708.58},
 {'close': 697.77, 'date': '2016-02-29', 'open': 700.32},
 {'close': 718.81, 'date': '2016-03-01', 'open': 703.62},
 {'close': 718.85, 'date': '2016-03-02', 'open': 719.0},
 {'close': 712.42, 'date': '2016-03-03', 'open': 718.68},
 {'close': 710.89, 'date': '2016-03-04', 'open': 714.99},
 {'close': 695.16, 'date': '2016-03-07', 'open': 706.9},
 {'close': 693.97, 'date': '2016-03-08', 'open': 688.59},
 {'close': 705.24, 'date': '2016-03-09', 'open': 698.47},
 {'close': 712.82, 'date': '2016-03-10', 'open': 708.12},
 {'close': 726.82, 'date': '2016-03-11', 'open': 720.0},
 {'close': 730.49, 'date': '2016-03-14', 'open': 726.81},
 {'close': 728.33, 'date': '2016-03-15', 'open': 726.92},
 {'close': 736.09, 'date': '2016-03-16', 'open': 726.37},
 {'close': 737.78, 'date': '2016-03-17', 'open': 736.45},
 {'close': 737.6, 'date': '2016-03-18', 'open': 741.86},
 {'close': 742.09, 'date': '2016-03-21', 'open': 736.5},
 {'close': 740.75, 'date': '2016-03-22', 'open': 737.46},
 {'close': 738.06, 'date': '2016-03-23', 'open': 742.36},
 {'close': 735.3, 'date': '2016-03-24', 'open': 732.01},
 {'close': 733.53, 'date': '2016-03-28', 'open': 736.79},
 {'close': 744.77, 'date': '2016-03-29', 'open': 734.59},
 {'close': 750.53, 'date': '2016-03-30', 'open': 750.1},
 {'close': 744.95, 'date': '2016-03-31', 'open': 749.25},
 {'close': 749.91, 'date': '2016-04-01', 'open': 738.6},
 {'close': 745.29, 'date': '2016-04-04', 'open': 750.06},
 {'close': 737.8, 'date': '2016-04-05', 'open': 738.0},
 {'close': 745.69, 'date': '2016-04-06', 'open': 735.77},
 {'close': 740.28, 'date': '2016-04-07', 'open': 745.37},
 {'close': 739.15, 'date': '2016-04-08', 'open': 743.97},
 {'close': 736.1, 'date': '2016-04-11', 'open': 743.02},
 {'close': 743.09, 'date': '2016-04-12', 'open': 738.0},
 {'close': 751.72, 'date': '2016-04-13', 'open': 749.16},
 {'close': 753.2, 'date': '2016-04-14', 'open': 754.01},
 {'close': 759.0, 'date': '2016-04-15', 'open': 753.98},
 {'close': 766.61, 'date': '2016-04-18', 'open': 760.46},
 {'close': 753.93, 'date': '2016-04-19', 'open': 769.51},
 {'close': 752.67, 'date': '2016-04-20', 'open': 758.0},
 {'close': 759.14, 'date': '2016-04-21', 'open': 755.38},
 {'close': 718.77, 'date': '2016-04-22', 'open': 726.3},
 {'close': 723.15, 'date': '2016-04-25', 'open': 716.1},
 {'close': 708.14, 'date': '2016-04-26', 'open': 725.42},
 {'close': 705.84, 'date': '2016-04-27', 'open': 707.29},
 {'close': 691.02, 'date': '2016-04-28', 'open': 708.26},
 {'close': 693.01, 'date': '2016-04-29', 'open': 690.7},
 {'close': 698.21, 'date': '2016-05-02', 'open': 697.63},
 {'close': 692.36, 'date': '2016-05-03', 'open': 696.87},
 {'close': 695.7, 'date': '2016-05-04', 'open': 690.49},
 {'close': 701.43, 'date': '2016-05-05', 'open': 697.7},
 {'close': 711.12, 'date': '2016-05-06', 'open': 698.38},
 {'close': 712.9, 'date': '2016-05-09', 'open': 712.0},
 {'close': 723.18, 'date': '2016-05-10', 'open': 716.75},
 {'close': 715.29, 'date': '2016-05-11', 'open': 723.41},
 {'close': 713.31, 'date': '2016-05-12', 'open': 717.06},
 {'close': 710.83, 'date': '2016-05-13', 'open': 711.93},
 {'close': 716.49, 'date': '2016-05-16', 'open': 709.13},
 {'close': 706.23, 'date': '2016-05-17', 'open': 715.99},
 {'close': 706.63, 'date': '2016-05-18', 'open': 703.67},
 {'close': 700.32, 'date': '2016-05-19', 'open': 702.36},
 {'close': 709.74, 'date': '2016-05-20', 'open': 701.62},
 {'close': 704.24, 'date': '2016-05-23', 'open': 706.53},
 {'close': 720.09, 'date': '2016-05-24', 'open': 706.86},
 {'close': 725.27, 'date': '2016-05-25', 'open': 720.76},
 {'close': 724.12, 'date': '2016-05-26', 'open': 722.87},
 {'close': 732.66, 'date': '2016-05-27', 'open': 724.01},
 {'close': 735.72, 'date': '2016-05-31', 'open': 731.74},
 {'close': 734.15, 'date': '2016-06-01', 'open': 734.53},
 {'close': 730.4, 'date': '2016-06-02', 'open': 732.5},
 {'close': 722.34, 'date': '2016-06-03', 'open': 729.27},
 {'close': 716.55, 'date': '2016-06-06', 'open': 724.91},
 {'close': 716.65, 'date': '2016-06-07', 'open': 719.84},
 {'close': 728.28, 'date': '2016-06-08', 'open': 723.96},
 {'close': 728.58, 'date': '2016-06-09', 'open': 722.87},
 {'close': 719.41, 'date': '2016-06-10', 'open': 719.47},
 {'close': 718.36, 'date': '2016-06-13', 'open': 716.51},
 {'close': 718.27, 'date': '2016-06-14', 'open': 716.48},
 {'close': 718.92, 'date': '2016-06-15', 'open': 719.0},
 {'close': 710.36, 'date': '2016-06-16', 'open': 714.91},
 {'close': 691.72, 'date': '2016-06-17', 'open': 708.65},
 {'close': 693.71, 'date': '2016-06-20', 'open': 698.77},
 {'close': 695.94, 'date': '2016-06-21', 'open': 698.4},
 {'close': 697.46, 'date': '2016-06-22', 'open': 699.06},
 {'close': 701.87, 'date': '2016-06-23', 'open': 697.45},
 {'close': 675.22, 'date': '2016-06-24', 'open': 675.17},
 {'close': 668.26, 'date': '2016-06-27', 'open': 671.0},
 {'close': 680.04, 'date': '2016-06-28', 'open': 678.97},
 {'close': 684.11, 'date': '2016-06-29', 'open': 683.0},
 {'close': 692.1, 'date': '2016-06-30', 'open': 685.47},
 {'close': 699.21, 'date': '2016-07-01', 'open': 692.2},
 {'close': 694.49, 'date': '2016-07-05', 'open': 696.06},
 {'close': 697.77, 'date': '2016-07-06', 'open': 689.98},
 {'close': 695.36, 'date': '2016-07-07', 'open': 698.08},
 {'close': 705.63, 'date': '2016-07-08', 'open': 699.5},
 {'close': 715.09, 'date': '2016-07-11', 'open': 708.05},
 {'close': 720.64, 'date': '2016-07-12', 'open': 719.12},
 {'close': 716.98, 'date': '2016-07-13', 'open': 723.62},
 {'close': 720.95, 'date': '2016-07-14', 'open': 721.58},
 {'close': 719.85, 'date': '2016-07-15', 'open': 725.73},
 {'close': 733.78, 'date': '2016-07-18', 'open': 722.71},
 {'close': 736.96, 'date': '2016-07-19', 'open': 729.89},
 {'close': 741.19, 'date': '2016-07-20', 'open': 737.33},
 {'close': 738.63, 'date': '2016-07-21', 'open': 740.36},
 {'close': 742.74, 'date': '2016-07-22', 'open': 741.86},
 {'close': 739.77, 'date': '2016-07-25', 'open': 740.67},
 {'close': 738.42, 'date': '2016-07-26', 'open': 739.04},
 {'close': 741.77, 'date': '2016-07-27', 'open': 738.28},
 {'close': 745.91, 'date': '2016-07-28', 'open': 747.04},
 {'close': 768.79, 'date': '2016-07-29', 'open': 772.71},
 {'close': 772.88, 'date': '2016-08-01', 'open': 761.09},
 {'close': 771.07, 'date': '2016-08-02', 'open': 768.69},
 {'close': 773.18, 'date': '2016-08-03', 'open': 767.18},
 {'close': 771.61, 'date': '2016-08-04', 'open': 772.22},
 {'close': 782.22, 'date': '2016-08-05', 'open': 773.78},
 {'close': 781.76, 'date': '2016-08-08', 'open': 782.0},
 {'close': 784.26, 'date': '2016-08-09', 'open': 781.1},
 {'close': 784.68, 'date': '2016-08-10', 'open': 783.75},
 {'close': 784.85, 'date': '2016-08-11', 'open': 785.0},
 {'close': 783.22, 'date': '2016-08-12', 'open': 781.5},
 {'close': 782.44, 'date': '2016-08-15', 'open': 783.75},
 {'close': 777.14, 'date': '2016-08-16', 'open': 780.3},
 {'close': 779.91, 'date': '2016-08-17', 'open': 777.32},
 {'close': 777.5, 'date': '2016-08-18', 'open': 780.01},
 {'close': 775.42, 'date': '2016-08-19', 'open': 775.0},
 {'close': 772.15, 'date': '2016-08-22', 'open': 773.27},
 {'close': 772.08, 'date': '2016-08-23', 'open': 775.48},
 {'close': 769.64, 'date': '2016-08-24', 'open': 770.58},
 {'close': 769.41, 'date': '2016-08-25', 'open': 767.0},
 {'close': 769.54, 'date': '2016-08-26', 'open': 769.0},
 {'close': 772.15, 'date': '2016-08-29', 'open': 768.74},
 {'close': 769.09, 'date': '2016-08-30', 'open': 769.33},
 {'close': 767.05, 'date': '2016-08-31', 'open': 767.01},
 {'close': 768.78, 'date': '2016-09-01', 'open': 769.25},
 {'close': 771.46, 'date': '2016-09-02', 'open': 773.01},
 {'close': 780.08, 'date': '2016-09-06', 'open': 773.45},
 {'close': 780.35, 'date': '2016-09-07', 'open': 780.0},
 {'close': 775.32, 'date': '2016-09-08', 'open': 778.59},
 {'close': 759.66, 'date': '2016-09-09', 'open': 770.1},
 {'close': 769.02, 'date': '2016-09-12', 'open': 755.13},
 {'close': 759.69, 'date': '2016-09-13', 'open': 764.48},
 {'close': 762.49, 'date': '2016-09-14', 'open': 759.61},
 {'close': 771.76, 'date': '2016-09-15', 'open': 762.89},
 {'close': 768.88, 'date': '2016-09-16', 'open': 769.75},
 {'close': 765.7, 'date': '2016-09-19', 'open': 772.42},
 {'close': 771.41, 'date': '2016-09-20', 'open': 769.0},
 {'close': 776.22, 'date': '2016-09-21', 'open': 772.66},
 {'close': 787.21, 'date': '2016-09-22', 'open': 780.0},
 {'close': 786.9, 'date': '2016-09-23', 'open': 786.59},
 {'close': 774.21, 'date': '2016-09-26', 'open': 782.74},
 {'close': 783.01, 'date': '2016-09-27', 'open': 775.5},
 {'close': 781.56, 'date': '2016-09-28', 'open': 777.85},
 {'close': 775.01, 'date': '2016-09-29', 'open': 781.44},
 {'close': 777.29, 'date': '2016-09-30', 'open': 776.33},
 {'close': 772.56, 'date': '2016-10-03', 'open': 774.25},
 {'close': 776.43, 'date': '2016-10-04', 'open': 776.03},
 {'close': 776.47, 'date': '2016-10-05', 'open': 779.31},
 {'close': 776.86, 'date': '2016-10-06', 'open': 779.0},
 {'close': 775.08, 'date': '2016-10-07', 'open': 779.66},
 {'close': 785.94, 'date': '2016-10-10', 'open': 777.71},
 {'close': 783.07, 'date': '2016-10-11', 'open': 786.66},
 {'close': 786.14, 'date': '2016-10-12', 'open': 783.76},
 {'close': 778.19, 'date': '2016-10-13', 'open': 781.22},
 {'close': 778.53, 'date': '2016-10-14', 'open': 781.65},
 {'close': 779.96, 'date': '2016-10-17', 'open': 779.8},
 {'close': 795.26, 'date': '2016-10-18', 'open': 787.85},
 {'close': 801.56, 'date': '2016-10-19', 'open': 798.86},
 {'close': 796.97, 'date': '2016-10-20', 'open': 803.3},
 {'close': 799.37, 'date': '2016-10-21', 'open': 795.0},
 {'close': 813.11, 'date': '2016-10-24', 'open': 804.9},
 {'close': 807.67, 'date': '2016-10-25', 'open': 816.68},
 {'close': 799.07, 'date': '2016-10-26', 'open': 806.34},
 {'close': 795.35, 'date': '2016-10-27', 'open': 801.0},
 {'close': 795.37, 'date': '2016-10-28', 'open': 808.35},
 {'close': 784.54, 'date': '2016-10-31', 'open': 795.47},
 {'close': 783.61, 'date': '2016-11-01', 'open': 782.89},
 {'close': 768.7, 'date': '2016-11-02', 'open': 778.2},
 {'close': 762.13, 'date': '2016-11-03', 'open': 767.25},
 {'close': 762.02, 'date': '2016-11-04', 'open': 750.66},
 {'close': 782.52, 'date': '2016-11-07', 'open': 774.5},
 {'close': 790.51, 'date': '2016-11-08', 'open': 783.4},
 {'close': 785.31, 'date': '2016-11-09', 'open': 779.94},
 {'close': 762.56, 'date': '2016-11-10', 'open': 791.17},
 {'close': 754.02, 'date': '2016-11-11', 'open': 756.54},
 {'close': 736.08, 'date': '2016-11-14', 'open': 755.6},
 {'close': 758.49, 'date': '2016-11-15', 'open': 746.97},
 {'close': 764.48, 'date': '2016-11-16', 'open': 755.2},
 {'close': 771.23, 'date': '2016-11-17', 'open': 766.92},
 {'close': 760.54, 'date': '2016-11-18', 'open': 771.37},
 {'close': 769.2, 'date': '2016-11-21', 'open': 762.61},
 {'close': 768.27, 'date': '2016-11-22', 'open': 772.63},
 {'close': 760.99, 'date': '2016-11-23', 'open': 767.73},
 {'close': 761.68, 'date': '2016-11-25', 'open': 764.26},
 {'close': 768.24, 'date': '2016-11-28', 'open': 760.0},
 {'close': 770.84, 'date': '2016-11-29', 'open': 771.53},
 {'close': 758.04, 'date': '2016-11-30', 'open': 770.07},
 {'close': 747.92, 'date': '2016-12-01', 'open': 757.44},
 {'close': 750.5, 'date': '2016-12-02', 'open': 744.59},
 {'close': 762.52, 'date': '2016-12-05', 'open': 757.71},
 {'close': 759.11, 'date': '2016-12-06', 'open': 764.73},
 {'close': 771.19, 'date': '2016-12-07', 'open': 761.0},
 {'close': 776.42, 'date': '2016-12-08', 'open': 772.48},
 {'close': 789.29, 'date': '2016-12-09', 'open': 780.0},
 {'close': 789.27, 'date': '2016-12-12', 'open': 785.04},
 {'close': 796.1, 'date': '2016-12-13', 'open': 793.9},
 {'close': 797.07, 'date': '2016-12-14', 'open': 797.4},
 {'close': 797.85, 'date': '2016-12-15', 'open': 797.34},
 {'close': 790.8, 'date': '2016-12-16', 'open': 800.4},
 {'close': 794.2, 'date': '2016-12-19', 'open': 790.22},
 {'close': 796.42, 'date': '2016-12-20', 'open': 796.76},
 {'close': 794.56, 'date': '2016-12-21', 'open': 795.84},
 {'close': 791.26, 'date': '2016-12-22', 'open': 792.36},
 {'close': 789.91, 'date': '2016-12-23', 'open': 790.9},
 {'close': 791.55, 'date': '2016-12-27', 'open': 790.68},
 {'close': 785.05, 'date': '2016-12-28', 'open': 793.7},
 {'close': 782.79, 'date': '2016-12-29', 'open': 783.33},
 {'close': 771.82, 'date': '2016-12-30', 'open': 782.75},
 {'close': 786.14, 'date': '2017-01-03', 'open': 778.81},
 {'close': 786.9, 'date': '2017-01-04', 'open': 788.36},
 {'close': 794.02, 'date': '2017-01-05', 'open': 786.08},
 {'close': 806.15, 'date': '2017-01-06', 'open': 795.26},
 {'close': 806.65, 'date': '2017-01-09', 'open': 806.4},
 {'close': 804.79, 'date': '2017-01-10', 'open': 807.86},
 {'close': 807.91, 'date': '2017-01-11', 'open': 805.0},
 {'close': 806.36, 'date': '2017-01-12', 'open': 807.14},
 {'close': 807.88, 'date': '2017-01-13', 'open': 807.48},
 {'close': 804.61, 'date': '2017-01-17', 'open': 807.08},
 {'close': 806.07, 'date': '2017-01-18', 'open': 805.81},
 {'close': 802.175, 'date': '2017-01-19', 'open': 805.12},
 {'close': 805.02, 'date': '2017-01-20', 'open': 806.91},
 {'close': 819.31, 'date': '2017-01-23', 'open': 807.25},
 {'close': 823.87, 'date': '2017-01-24', 'open': 822.3},
 {'close': 835.67, 'date': '2017-01-25', 'open': 829.62},
 {'close': 832.15, 'date': '2017-01-26', 'open': 837.81},
 {'close': 823.31, 'date': '2017-01-27', 'open': 834.71},
 {'close': 802.32, 'date': '2017-01-30', 'open': 814.66},
 {'close': 796.79, 'date': '2017-01-31', 'open': 796.86},
 {'close': 795.695, 'date': '2017-02-01', 'open': 799.68},
 {'close': 798.53, 'date': '2017-02-02', 'open': 793.8},
 {'close': 801.49, 'date': '2017-02-03', 'open': 802.99},
 {'close': 801.34, 'date': '2017-02-06', 'open': 799.7},
 {'close': 806.97, 'date': '2017-02-07', 'open': 803.99},
 {'close': 808.38, 'date': '2017-02-08', 'open': 807.0},
 {'close': 809.56, 'date': '2017-02-09', 'open': 809.51},
 {'close': 813.67, 'date': '2017-02-10', 'open': 811.7},
 {'close': 819.24, 'date': '2017-02-13', 'open': 816.0},
 {'close': 820.45, 'date': '2017-02-14', 'open': 819.0},
 {'close': 818.98, 'date': '2017-02-15', 'open': 819.36},
 {'close': 824.16, 'date': '2017-02-16', 'open': 819.93},
 {'close': 828.07, 'date': '2017-02-17', 'open': 823.02},
 {'close': 831.66, 'date': '2017-02-21', 'open': 828.66},
 {'close': 830.76, 'date': '2017-02-22', 'open': 828.66},
 {'close': 831.33, 'date': '2017-02-23', 'open': 830.12},
 {'close': 828.64, 'date': '2017-02-24', 'open': 827.73},
 {'close': 829.28, 'date': '2017-02-27', 'open': 824.55},
 {'close': 823.21, 'date': '2017-02-28', 'open': 825.61},
 {'close': 835.24, 'date': '2017-03-01', 'open': 828.85},
 {'close': 830.63, 'date': '2017-03-02', 'open': 833.85},
 {'close': 829.08, 'date': '2017-03-03', 'open': 830.56},
 {'close': 827.78, 'date': '2017-03-06', 'open': 826.95},
 {'close': 831.91, 'date': '2017-03-07', 'open': 827.4},
 {'close': 835.37, 'date': '2017-03-08', 'open': 833.51},
 {'close': 838.68, 'date': '2017-03-09', 'open': 836.0},
 {'close': 843.25, 'date': '2017-03-10', 'open': 843.28},
 {'close': 845.54, 'date': '2017-03-13', 'open': 844.0},
 {'close': 845.62, 'date': '2017-03-14', 'open': 843.64},
 {'close': 847.2, 'date': '2017-03-15', 'open': 847.59},

In [32]:
goog_df = pd.DataFrame.from_dict(goog_df, orient='columns')
GOOG_df = goog_df[:443]
GOOG_df

      close        date    open
0    716.92  2015-10-29  710.50
1    710.81  2015-10-30  715.73
2    721.11  2015-11-02  711.06
3    722.16  2015-11-03  718.86
4    728.11  2015-11-04  722.00
5    731.25  2015-11-05  729.47
6    733.76  2015-11-06  731.50
7    724.89  2015-11-09  730.20
8    728.32  2015-11-10  724.40
9    735.40  2015-11-11  732.46
10   731.23  2015-11-12  731.00
11   717.00  2015-11-13  729.17
12   728.96  2015-11-16  715.60
13   725.30  2015-11-17  729.29
14   740.00  2015-11-18  727.58
15   738.41  2015-11-19  738.74
16   756.60  2015-11-20  746.53
17   755.98  2015-11-23  757.45
18   748.28  2015-11-24  752.00
19   748.15  2015-11-25  748.14
20   750.26  2015-11-27  748.46
21   742.60  2015-11-30  748.81
22   767.04  2015-12-01  747.11
23   762.38  2015-12-02  768.90
24   752.54  2015-12-03  766.01
25   766.81  2015-12-04  753.10
26   763.25  2015-12-07  767.77
27   762.37  2015-12-08  757.89
28   751.61  2015-12-09  759.17
29   749.46  2015-12-10  752.85
30   738.87  2015-12-11  741.16
31   747.77  2015-12-14  741.79
32   743.40  2015-12-15  753.00
33   758.09  2015-12-16  750.00
34   749.43  2015-12-17  762.42
35   739.31  2015-12-18  746.51
36   747.77  2015-12-21  746.13
37   750.00  2015-12-22  751.65
38   750.31  2015-12-23  753.47
39   748.40  2015-12-24  749.55
40   762.51  2015-12-28  752.92
41   776.60  2015-12-29  766.69
42   771.00  2015-12-30  776.60
43   758.88  2015-12-31  769.50
44   741.84  2016-01-04  743.00
45   742.58  2016-01-05  746.45
46   743.62  2016-01-06  730.00
47   726.39  2016-01-07  730.31
48   714.47  2016-01-08  731.45
49   716.03  2016-01-11  716.61
..      ...         ...     ...
393  948.82  2017-05-23  947.92
394  954.96  2017-05-24  952.98
395  969.54  2017-05-25  957.33
396  971.47  2017-05-26  969.70
397  975.88  2017-05-30  970.31
398  964.86  2017-05-31  975.02
399  966.95  2017-06-01  968.95
400  975.60  2017-06-02  969.46
401  983.68  2017-06-05  976.55
402  976.57  2017-06-06  983.16
403  981.08  2017-06-07  979.65
404  983.41  2017-06-08  982.35
405  949.83  2017-06-09  984.50
406  942.90  2017-06-12  939.56
407  953.40  2017-06-13  951.91
408  950.76  2017-06-14  959.92
409  942.31  2017-06-15  933.97
410  939.78  2017-06-16  940.00
411  957.37  2017-06-19  949.96
412  950.63  2017-06-20  957.52
413  959.45  2017-06-21  953.64
414  957.09  2017-06-22  958.70
415  965.59  2017-06-23  956.83
416  952.27  2017-06-26  969.90
417  927.33  2017-06-27  942.46
418  940.49  2017-06-28  929.00
419  917.79  2017-06-29  929.92
420  908.73  2017-06-30  926.05
421  898.70  2017-07-03  912.18
422  911.94  2017-07-05  901.76
423  906.69  2017-07-06  904.12
424  918.59  2017-07-07  908.85
425  928.80  2017-07-10  921.77
426  930.09  2017-07-11  929.54
427  943.83  2017-07-12  938.68
428  947.16  2017-07-13  946.29
429  955.99  2017-07-14  952.00
430  953.42  2017-07-17  957.00
431  965.40  2017-07-18  953.00
432  970.89  2017-07-19  967.84
433  968.15  2017-07-20  975.00
434  972.92  2017-07-21  962.25
435  980.34  2017-07-24  972.22
436  950.70  2017-07-25  953.81
437  947.80  2017-07-26  954.68
438  934.09  2017-07-27  951.78
439  941.53  2017-07-28  929.40
440  930.50  2017-07-31  941.89
441  930.83  2017-08-01  932.38
442  930.39  2017-08-02  928.61

[443 rows x 3 columns]

In [33]:
#now combinining into 1 data frame
json_df = pd.concat([AAPL_df, AMAZN_df, GOOG_df], axis=1)
json_df.columns = ['aapl_cl', 'aapl_dt', 'aapl_op', 'amzn_cl', 'amzn_dt', 'amzn_op', 'goog_cl', 'goog_dt', 'goog_op']

In [34]:
json_df

,aapl_cl,aapl_dt,aapl_op,amzn_cl,amzn_dt,amzn_op,goog_cl,goog_dt,goog_op
0,120.530,2015-10-29,118.70,626.550,2015-10-29,617.70,716.92,2015-10-29,710.50
1,119.500,2015-10-30,120.99,625.900,2015-10-30,626.01,710.81,2015-10-30,715.73
2,121.180,2015-11-02,119.87,628.350,2015-11-02,627.13,721.11,2015-11-02,711.06
3,122.570,2015-11-03,120.79,625.310,2015-11-03,629.53,722.16,2015-11-03,718.86
4,122.000,2015-11-04,123.13,640.950,2015-11-04,627.76,728.11,2015-11-04,722.00
5,120.920,2015-11-05,121.85,655.650,2015-11-05,647.10,731.25,2015-11-05,729.47
6,121.060,2015-11-06,121.11,659.370,2015-11-06,655.00,733.76,2015-11-06,731.50
7,120.570,2015-11-09,120.96,655.490,2015-11-09,658.65,724.89,2015-11-09,730.20
8,116.770,2015-11-10,116.90,659.680,2015-11-10,651.01,728.32,2015-11-10,724.40
9,116.110,2015-11-11,116.37,673.250,2015-11-11,663.25,735.40,2015-11-11,732.46
10,115.720,2015-11-12,116.26,665.600,2015-11-12,673.00,731.23,2015-11-12,731.00
11,112.340,2015-11-13,115.20,642.350,2015-11-13,663.57,717.00,2015-11-13,729.17
12,114.175,2015-11-16,111.38,647.810,2015-11-16,640.92,728.96,2015-11-16,715.60
13,113.690,2015-11-17,114.92,643.300,2015-11-17,650.65,725.30,2015-11-17,729.29
14,117.290,2015-11-18,115.76,663.540,2015-11-18,646.51,740.00,2015-11-18,727.58
15,118.780,2015-11-19,117.64,661.270,2015-11-19,664.99,738.41,2015-11-19,738.74
16,119.300,2015-11-20,119.20,668.450,2015-11-20,667.94,756.60,2015-11-20,746.53
17,117.750,2015-11-23,119.27,678.990,2015-11-23,671.50,755.98,2015-11-23,757.45
18,118.880,2015-11-24,117.33,671.150,2015-11-24,674.14,748.28,2015-11-24,752.00
19,118.030,2015-11-25,119.21,675.340,2015-11-25,675.00,748.15,2015-11-25,748.14
20,117.810,2015-11-27,118.29,673.260,2015-11-27,680.80,750.26,2015-11-27,748.46
21,118.300,2015-11-30,117.99,664.800,2015-11-30,675.90,742.60,2015-11-30,748.81
22,117.340,2015-12-01,118.75,679.060,2015-12-01,673.75,767.04,2015-12-01,747.11
23,116.280,2015-12-02,117.05,676.010,2015-12-02,681.00,762.38,2015-12-02,768.90
24,115.200,2015-12-03,116.55,666.250,2015-12-03,679.44,752.54,2015-12-03,766.01
25,119.030,2015-12-04,115.29,672.640,2015-12-04,666.00,766.81,2015-12-04,753.10
26,118.280,2015-12-07,118.98,669.830,2015-12-07,674.74,763.25,2015-12-07,767.77
27,118.230,2015-12-08,117.52,677.330,2015-12-08,663.13,762.37,2015-12-08,757.89
28,115.620,2015-12-09,117.64,664.790,2015-12-09,678.00,751.61,2015-12-09,759.17
29,116.170,2015-12-10,116.04,662.320,2015-12-10,665.59,749.46,2015-12-10,752.85
30,113.180,2015-12-11,115.19,640.150,2015-12-11,651.23,738.87,2015-12-11,741.16
31,112.480,2015-12-14,112.18,657.910,2015-12-14,641.75,747.77,2015-12-14,741.79
32,110.490,2015-12-15,111.94,658.640,2015-12-15,665.03,743.40,2015-12-15,753.00
33,111.340,2015-12-16,111.07,675.770,2015-12-16,663.56,758.09,2015-12-16,750.00
34,108.980,2015-12-17,112.02,670.650,2015-12-17,680.00,749.43,2015-12-17,762.42
35,106.030,2015-12-18,108.91,664.140,2015-12-18,668.65,739.31,2015-12-18,746.51
36,107.330,2015-12-21,107.28,664.510,2015-12-21,668.50,747.77,2015-12-21,746.13
37,107.230,2015-12-22,107.40,663.150,2015-12-22,666.83,750.00,2015-12-22,751.65
38,108.610,2015-12-23,107.27,663.700,2015-12-23,666.50,750.31,2015-12-23,753.47
39,108.030,2015-12-24,109.00,662.790,2015-12-24,663.35,748.40,2015-12-24,749.55
40,106.820,2015-12-28,107.59,675.200,2015-12-28,665.56,762.51,2015-12-28,752.92
41,108.740,2015-12-29,106.96,693.970,2015-12-29,677.98,776.60,2015-12-29,766.69
42,107.320,2015-12-30,108.58,689.070,2015-12-30,691.89,771.00,2015-12-30,776.60
43,105.260,2015-12-31,107.01,675.890,2015-12-31,686.08,758.88,2015-12-31,769.50
44,105.350,2016-01-04,102.61,636.990,2016-01-04,656.29,741.84,2016-01-04,743.00
45,102.710,2016-01-05,105.75,633.790,2016-01-05,646.86,742.58,2016-01-05,746.45
46,100.700,2016-01-06,100.56,632.650,2016-01-06,622.00,743.62,2016-01-06,730.00
47,96.450,2016-01-07,98.68,607.940,2016-01-07,621.80,726.39,2016-01-07,730.31
48,96.960,2016-01-08,98.55,607.050,2016-01-08,619.66,714.47,2016-01-08,731.45
49,98.530,2016-01-11,98.97,617.740,2016-01-11,612.48,716.03,2016-01-11,716.61
...,...,...,...,...,...,...,...,...,...
393,153.800,2017-05-23,154.90,971.540,2017-05-23,975.02,948.82,2017-05-23,947.92
394,153.340,2017-05-24,153.84,980.350,2017-05-24,976.00,954.96,2017-05-24,952.98
395,153.870,2017-05-25,153.73,993.380,2017-05-25,984.85,969.54,2017-05-25,957.33
396,153.610,2017-05-26,154.00,995.780,2017-05-26,995.00,971.47,2017-05-26,969.70
397,153.670,2017-05-30,153.42,996.700,2017-05-30,996.51,975.88,2017-05-30,970.31
398,152.760,2017-05-31,153.97,994.620,2017-05-31,1000.00,964.86,2017-05-31,975.02
399,153.180,2017-06-01,153.17,995.950,2017-06-01,998.59,966.95,2017-06-01,968.95
400,155.450,2017-06-02,153.58,1006.730,2017-06-02,998.99,975.60,2017-06-02,969.46
401,153.930,2017-06-05,154.34,1011.340,2017-06-05,1007.23,983.68,2017-06-05,976.55
402,154.450,2017-06-06,153.90,1002.970,2017-06-06,1012.00,976.57,2017-06-06,983.16
403,155.370,2017-06-07,155.02,1010.070,2017-06-07,1005.95,981.08,2017-06-07,979.65
404,154.990,2017-06-08,155.25,1009.940,2017-06-08,1012.06,983.41,2017-06-08,982.35
405,148.980,2017-06-09,155.19,978.310,2017-06-09,1012.50,949.83,2017-06-09,984.50
406,145.320,2017-06-12,145.74,964.830,2017-06-12,967.00,942.90,2017-06-12,939.56
407,146.590,2017-06-13,147.16,980.790,2017-06-13,977.99,953.40,2017-06-13,951.91
408,145.160,2017-06-14,147.50,976.470,2017-06-14,988.59,950.76,2017-06-14,959.92
409,144.290,2017-06-15,143.32,964.170,2017-06-15,958.70,942.31,2017-06-15,933.97
410,142.270,2017-06-16,143.78,987.710,2017-06-16,996.00,939.78,2017-06-16,940.00
411,146.340,2017-06-19,143.66,995.170,2017-06-19,1017.00,957.37,2017-06-19,949.96
412,145.010,2017-06-20,146.87,992.590,2017-06-20,998.00,950.63,2017-06-20,957.52
413,145.870,2017-06-21,145.52,1002.230,2017-06-21,998.70,959.45,2017-06-21,953.64
414,145.630,2017-06-22,145.77,1001.300,2017-06-22,1002.23,957.09,2017-06-22,958.70
415,146.350,2017-06-23,145.13,1003.740,2017-06-23,1002.54,965.59,2017-06-23,956.83
416,145.820,2017-06-26,147.17,993.980,2017-06-26,1008.50,952.27,2017-06-26,969.90
417,143.740,2017-06-27,145.01,976.780,2017-06-27,990.69,927.33,2017-06-27,942.46
418,145.830,2017-06-28,144.49,990.330,2017-06-28,978.55,940.49,2017-06-28,929.00
419,143.680,2017-06-29,144.71,975.930,2017-06-29,979.00,917.79,2017-06-29,929.92
420,144.020,2017-06-30,144.45,968.000,2017-06-30,980.12,908.73,2017-06-30,926.05
421,143.500,2017-07-03,144.88,953.660,2017-07-03,972.79,898.70,2017-07-03,912.18
422,144.090,2017-07-05,143.69,971.400,2017-07-05,961.53,911.94,2017-07-05,901.76
423,142.730,2017-07-06,143.02,965.140,2017-07-06,964.66,906.69,2017-07-06,904.12
424,144.180,2017-07-07,142.90,978.760,2017-07-07,969.55,918.59,2017-07-07,908.85
425,145.060,2017-07-10,144.11,996.470,2017-07-10,985.00,928.80,2017-07-10,921.77
426,145.530,2017-07-11,144.73,994.130,2017-07-11,993.00,930.09,2017-07-11,929.54
427,145.740,2017-07-12,145.87,1006.510,2017-07-12,1000.65,943.83,2017-07-12,938.68
428,147.770,2017-07-13,145.50,999.855,2017-07-13,1004.62,947.16,2017-07-13,946.29
429,149.040,2017-07-14,147.97,1001.810,2017-07-14,1002.40,955.99,2017-07-14,952.00
430,149.560,2017-07-17,148.82,1010.040,2017-07-17,1004.69,953.42,2017-07-17,957.00
431,150.080,2017-07-18,149.20,1024.380,2017-07-18,1006.00,965.40,2017-07-18,953.00
432,151.020,2017-07-19,150.48,1026.870,2017-07-19,1025.00,970.89,2017-07-19,967.84
433,150.340,2017-07-20,151.50,1028.700,2017-07-20,1031.59,968.15,2017-07-20,975.00
434,150.270,2017-07-21,149.99,1025.670,2017-07-21,1021.28,972.92,2017-07-21,962.25
435,152.090,2017-07-24,150.58,1038.950,2017-07-24,1028.34,980.34,2017-07-24,972.22
436,152.740,2017-07-25,151.80,1039.870,2017-07-25,1038.05,950.70,2017-07-25,953.81
437,153.460,2017-07-26,153.35,1052.800,2017-07-26,1043.20,947.80,2017-07-26,954.68
438,150.560,2017-07-27,153.75,1046.000,2017-07-27,1069.55,934.09,2017-07-27,951.78
439,149.500,2017-07-28,149.89,1020.040,2017-07-28,1012.14,941.53,2017-07-28,929.40
440,148.850,2017-07-31,149.90,987.780,2017-07-31,1019.05,930.50,2017-07-31,941.89
441,150.050,2017-08-01,149.10,996.190,2017-08-01,996.11,930.83,2017-08-01,932.38
442,157.140,2017-08-02,159.28,995.890,2017-08-02,1001.77,930.39,2017-08-02,928.61

In [35]:
#i will now run summary statistics on my completed data frame
json_df.describe()

          aapl_cl     aapl_op     amzn_cl      amzn_op     goog_cl     goog_op
count  443.000000  443.000000   443.00000   443.000000  443.000000  443.000000
mean   117.780905  117.702376   766.04798   766.053600  788.665020  788.571603
std     18.846005   18.842831   131.85667   132.189512   78.096494   78.041465
min     90.340000   90.000000   482.07000   478.010000  668.260000  667.850000
25%    102.980000  102.630000   669.14000   667.385000  731.240000  730.100000
50%    112.880000  113.000000   764.46000   764.550000  771.190000  771.530000
75%    136.815000  136.755000   845.42500   844.960000  824.015000  823.785000
max    157.140000  159.280000  1052.80000  1069.550000  983.680000  984.500000

In [36]:
#now i will include additional percentiles
json_df.describe(percentiles=[.01, .05, .95, .99])

          aapl_cl     aapl_op     amzn_cl      amzn_op     goog_cl     goog_op
count  443.000000  443.000000   443.00000   443.000000  443.000000  443.000000
mean   117.780905  117.702376   766.04798   766.053600  788.665020  788.571603
std     18.846005   18.842831   131.85667   132.189512   78.096494   78.041465
min     90.340000   90.000000   482.07000   478.010000  668.260000  667.850000
1%      92.749400   92.947800   505.18920   514.387600  682.542800  676.766000
5%      94.408000   94.451000   559.47300   560.202000  695.715000  697.468000
50%    112.880000  113.000000   764.46000   764.550000  771.190000  771.530000
95%    152.758000  153.332000   996.44200  1001.658000  953.287000  953.793000
99%    155.416400  155.118600  1027.93140  1026.937200  976.280200  975.907400
max    157.140000  159.280000  1052.80000  1069.550000  983.680000  984.500000

In [37]:
#since extensive work was already done to fit data into one data frame, i will now prcoeed to visualizing the data
#here is Apple's closing price for those 443 observations
sns.distplot(json_df.aapl_cl, kde=True)

In [41]:
#here is Amazon's closing price for those observations
sns.distplot(json_df.amzn_cl, kde=True)

In [42]:
#finally, here is Google's
sns.distplot(json_df.goog_cl, kde=True)

In [45]:
#now using sql file on public sentiment toward various airlines from tweets
import sqlite3

In [51]:
conn = sqlite3.connect("/Users/marshallringwood/Desktop/ECON213R/database.sqlite")
airline_df = pd.read_sql_query("select * from Tweets;", conn)
airline_df
#i'll use: airline_sentiment, negativereason, negativereason_confidence, airline

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,567588278875213824,neutral,1.0000,,,Delta,,JetBlueNews,,0,@JetBlue's new CEO seeks the right balance to ...,,2015-02-16 23:36:05 -0800,USA,Sydney
1,567590027375702016,negative,1.0000,Can't Tell,0.6503,Delta,,nesi_1992,,0,@JetBlue is REALLY getting on my nerves !! 😡😡 ...,,2015-02-16 23:43:02 -0800,undecided,Pacific Time (US & Canada)
2,567591480085463040,negative,1.0000,Late Flight,0.346,United,,CPoutloud,,0,@united yes. We waited in line for almost an h...,,2015-02-16 23:48:48 -0800,"Washington, DC",
3,567592368451248130,negative,1.0000,Late Flight,1,United,,brenduch,,0,@united the we got into the gate at IAH on tim...,,2015-02-16 23:52:20 -0800,,Buenos Aires
4,567594449874587648,negative,1.0000,Customer Service Issue,0.3451,Southwest,,VahidESQ,,0,@SouthwestAir its cool that my bags take a bit...,,2015-02-17 00:00:36 -0800,"Los Angeles, CA",Pacific Time (US & Canada)
5,567594579310825473,negative,1.0000,Bad Flight,0.6707,United,,brenduch,,0,@united and don't hope for me having a nicer f...,,2015-02-17 00:01:07 -0800,,Buenos Aires
6,567595670463205376,negative,1.0000,Late Flight,1,United,,CRomerDome,,0,@united I like delays less than you because I'...,,2015-02-17 00:05:27 -0800,"Portland, OR",Pacific Time (US & Canada)
7,567614049425555457,negative,1.0000,Customer Service Issue,0.3545,United,,JustOGG,,0,"@united, link to current status of flights/air...",,2015-02-17 01:18:29 -0800,Tweets = My Opinion,Eastern Time (US & Canada)
8,567617081336950784,negative,1.0000,Customer Service Issue,1,Southwest,,mrshossruns,,0,@SouthwestAir you guys there? Are we on hour 2...,,2015-02-17 01:30:32 -0800,,Eastern Time (US & Canada)
9,567617486703853568,negative,1.0000,Customer Service Issue,0.6797,United,,feliciastoler,,0,@united I tried 2 DM it would not go thru... n...,"[0.0, 0.0]",2015-02-17 01:32:09 -0800,New Jersey,Central Time (US & Canada)
10,567623209026334720,negative,0.6337,Flight Booking Problems,0.6337,United,,markhlyon,,0,"Wanted to get my bag benefit, but instead get ...","[38.9058375, -77.00423674]",2015-02-17 01:54:53 -0800,"Washington, DC",Eastern Time (US & Canada)
11,567627253991735296,negative,1.0000,Bad Flight,0.3611,United,,DBsViewOnThings,,0,@united please see a flight attendant for what...,,2015-02-17 02:10:58 -0800,,Atlantic Time (Canada)
12,567630296783155203,negative,1.0000,Customer Service Issue,0.6752,United,,ljsbrooks,,0,@united still waiting for a reply,,2015-02-17 02:23:03 -0800,,
13,567634106058821632,neutral,1.0000,,,United,,gwaki,,0,@united even though technically after I land I...,,2015-02-17 02:38:11 -0800,,Central Time (US & Canada)
14,567643252753694721,neutral,1.0000,,,US Airways,,ashenfaced,,0,@USAirways how's us 1797 looking today?,,2015-02-17 03:14:32 -0800,Brighton,
15,567655489119326209,positive,1.0000,,,Southwest,,rjp1208,,0,@SouthwestAir nice work on the update!,,2015-02-17 04:03:09 -0800,,Pacific Time (US & Canada)
16,567663136082513920,negative,1.0000,Lost Luggage,1,United,,hannahtorney,,0,@united i have items of sentimental value that...,,2015-02-17 04:33:32 -0800,Omagh/Belfast,London
17,567663504102940672,negative,1.0000,Late Flight,0.6605,Southwest,,followkashyap,,0,@SouthwestAir We have been stuck in SJU for se...,,2015-02-17 04:35:00 -0800,USA,Eastern Time (US & Canada)
18,567667301067915264,neutral,1.0000,,,Delta,,BritishAirNews,,0,"@JetBlue CEO weighs profits, flyers - @Chronic...",,2015-02-17 04:50:05 -0800,UK,Sydney
19,567670985403285504,negative,1.0000,Customer Service Issue,1,US Airways,,sevnthstar,,0,@USAirways @AmericanAir How r u supposed to ch...,,2015-02-17 05:04:44 -0800,often underwater,Pacific Time (US & Canada)
20,567671602280923136,positive,1.0000,,,Delta,,twinkletaters,,0,@JetBlue Thanks! Her flight leaves at 2 but sh...,"[32.07301184, -81.09362691]",2015-02-17 05:07:11 -0800,"Savannah, GA",
21,567676400933416960,negative,1.0000,Late Flight,0.7098,United,,MiKasuga,,0,"@United is officially the worst, most delayed,...",,2015-02-17 05:26:15 -0800,"New York, NY",Eastern Time (US & Canada)
22,567676626855419904,negative,1.0000,Customer Service Issue,0.6364,Southwest,,WorkingWify,,0,@SouthwestAir won't answer their phones #Horri...,,2015-02-17 05:27:09 -0800,America,
23,567679487383699456,negative,1.0000,Customer Service Issue,0.7188,US Airways,,DonnyYardas,,0,@USAirways reservations had me on hold for 2 h...,,2015-02-17 05:38:31 -0800,Somewhere Creating,Eastern Time (US & Canada)
24,567680108002291712,positive,0.6645,,0,Delta,,TravellerLukose,,0,@JetBlue No worries. Delay was minor and dealt...,,2015-02-17 05:40:59 -0800,,
25,567686758708817921,neutral,0.6890,,0,Southwest,,Tinygami,,0,@SouthwestAir Is it a temporary site glitch or...,,2015-02-17 06:07:25 -0800,Michigan,Tehran
26,567686845903826947,neutral,0.6579,,0,United,,AsianAdidasGirl,,0,@united clicked on the link and got this? #con...,"[30.09009009, -95.64621813]",2015-02-17 06:07:45 -0800,Houston,Central Time (US & Canada)
27,567688325276770306,neutral,0.6957,,0,Southwest,,DubCook,,0,"@SouthwestAir Guys, we've got to do something ...","[21.05483165, -86.78164351]",2015-02-17 06:13:38 -0800,"Downtown Dallas, Texas",Central Time (US & Canada)
28,567688411289755648,negative,1.0000,Cancelled Flight,0.6466,Southwest,,kabell87,,0,@SouthwestAir flight was Cancelled Flightled a...,,2015-02-17 06:13:59 -0800,,
29,567690417265975296,neutral,0.6739,,,Delta,,JulianBOGJB,,0,@JetBlue really caring??,,2015-02-17 06:21:57 -0800,Colombia,
30,567692251954827265,negative,1.0000,Flight Attendant Complaints,1,Southwest,,MMKuderka,,0,@SouthwestAir allows other passengers 2 harass...,,2015-02-17 06:29:14 -0800,,Arizona
31,567692504397803520,negative,1.0000,Flight Booking Problems,0.6709,Southwest,,kabell87,,0,@SouthwestAir this is really unhelpful. Why c...,,2015-02-17 06:30:14 -0800,,
32,567695310860730369,negative,1.0000,Late Flight,1,Delta,,EBlaikie,,0,@JetBlue sitting on the plane in JFK waiting t...,,2015-02-17 06:41:24 -0800,,
33,567696188602712064,negative,1.0000,Late Flight,1,Delta,,elowthers,,0,@JetBlue A flight delay due to pilots overslee...,,2015-02-17 06:44:53 -0800,,
34,567698031081160704,negative,1.0000,Customer Service Issue,0.6963,US Airways,,MarkKersten,,0,.@USAirways we have no choice but to pay anoth...,,2015-02-17 06:52:12 -0800,"London, UK",Quito
35,567701830805618688,positive,1.0000,,,United,,scherzva,,0,"@united New Apple crâpe, amazing! Live from UA...",,2015-02-17 07:07:18 -0800,"ÜT: 34.188976,-118.613497",Eastern Time (US & Canada)
36,567702414157824000,negative,1.0000,Cancelled Flight,0.6526,Southwest,,lucasdavidson,,0,@SouthwestAir on hold for 2 hours and then you...,,2015-02-17 07:09:37 -0800,,Eastern Time (US & Canada)
37,567703258425081857,negative,1.0000,Late Flight,0.7073,United,,wackydunks,,0,.@united call my work and tell them it's your ...,,2015-02-17 07:12:58 -0800,"grand rapids, michigan",Eastern Time (US & Canada)
38,567704339448209409,negative,1.0000,Can't Tell,0.6843,Southwest,,Raven_TheGreat,,0,@SouthwestAir why have you guys jacked up the ...,,2015-02-17 07:17:16 -0800,"Dallas, TX",Central Time (US & Canada)
39,567710245053407232,negative,1.0000,Customer Service Issue,0.6838,US Airways,,CharNewsJunkie,,0,@USAirways I have been on hold with your Gold ...,,2015-02-17 07:40:44 -0800,"Charlotte, North Carolina",Eastern Time (US & Canada)
40,567711860938772480,neutral,1.0000,,,United,,Jamie_Fisher886,,0,@united how much does it cost to check in an a...,,2015-02-17 07:47:09 -0800,Glasgow,London
41,567712600772050945,negative,0.6716,Late Flight,0.6716,US Airways,,sankeshw,,0,@USAirways we are on the 2pm flight FLL to PHL...,,2015-02-17 07:50:06 -0800,"North West, UK",Casablanca
42,567713338873118722,positive,0.6803,,0,Southwest,,DaxJeter,,0,@SouthwestAir thanks do yall expect to be oper...,,2015-02-17 07:53:02 -0800,"Nashville,TN",
43,567713868747902976,negative,1.0000,Customer Service Issue,0.6721,Southwest,,CBSsoxfan,,0,"@SouthwestAir husband on hold 2.5 hrs, got dis...",,2015-02-17 07:55:08 -0800,Rhode Island,
44,567713896627470336,negative,1.0000,Flight Attendant Complaints,1,United,,rachaeldoyle21,,0,@united Broken entertainment system on my 8 ho...,,2015-02-17 07:55:15 -0800,"Portsmouth, UK",
45,567714192980201472,negative,1.0000,longlines,0.3469,United,,lauralscott,,0,@united last night we waited forever at the ga...,"[0.0, 0.0]",2015-02-17 07:56:25 -0800,"ÜT: 40.976702,-72.210688",Quito
46,567715682918227970,negative,0.6701,Customer Service Issue,0.6701,Southwest,,kukalong,,0,@SouthwestAir Hoping you answer the phone today?,,2015-02-17 08:02:21 -0800,"Phoenix, AZ",Arizona
47,567715917983776772,negative,1.0000,Customer Service Issue,0.6966,Southwest,,sahandmirza,,0,@SouthwestAir been on hold for &gt;30 minutes ...,,2015-02-17 08:03:17 -0800,"San Francisco, CA",
48,567716378681933825,neutral,1.0000,,,Delta,,JetBlueNews,,0,"@JetBlue CEO weighs profits, flyers - @Chronic...",,2015-02-17 08:05:06 -0800,USA,Sydney
49,567716403117957120,negative,1.0000,Bad Flight,1,United,,tcfitz3,,0,@United - Ridiculous to fly outdated 757s anyw...,,2015-02-17 08:05:12 -0800,Houston,Central Time (US & Canada)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14435,570305063052283904,negative,1.0000,Bad Flight,0.67,American,,drhavoc,,0,@americanair thanks for no fresh food on my cr...,,2015-02-24 11:31:37 -0800,Tampa Bay,Eastern Time (US & Canada)
14436,570305078470557697,negative,1.0000,Customer Service Issue,1,Southwest,,Tim535353,,0,@SouthwestAir still no update text #2053 &amp;...,,2015-02-24 11:31:41 -0800,"St. Louis, MO",Central Time (US & Canada)
14437,570305098557091840,neutral,0.6472,,0,Delta,,culinarymindz,,0,@JetBlue update on Flight 462 would be appreci...,,2015-02-24 11:31:45 -0800,,
14438,570305234838429696,negative,1.0000,Customer Service Issue,0.6641,American,,TheOnlyJasonS,,1,@AmericanAir I sure hope you all can fix @USAi...,,2015-02-24 11:32:18 -0800,,
14439,570305264613765122,positive,1.0000,,,American,,jamucsb,,0,@AmericanAir thank you!,,2015-02-24 11:32:25 -0800,"Los Angeles, CA",Pacific Time (US & Canada)
14440,570305363859406848,negative,1.0000,Bad Flight,1,Delta,,Oneladyyouadore,,0,@JetBlue everyone is here but our pilots are n...,,2015-02-24 11:32:49 -0800,Georgia,Quito
14441,570305365159632899,neutral,0.3474,,0,American,,penyu1818,,0,"@AmericanAir DM the locator code, thanks.",,2015-02-24 11:32:49 -0800,,
14442,570305603056349184,neutral,0.6450,,0,United,,karenmcgregor86,,0,@united even on international flight Glasgow t...,,2015-02-24 11:33:46 -0800,"Kilmarnock, now Edinburgh.",Edinburgh
14443,570305647759265793,negative,1.0000,Customer Service Issue,1,Southwest,,cindyjwhitaker,,0,@SouthwestAir Very frustrated for the loooooon...,,2015-02-24 11:33:56 -0800,,Central Time (US & Canada)
14444,570306086475075585,neutral,0.6443,,,Southwest,,liveseasoned,,0,@SouthwestAir I'm teaching new #travelers how ...,,2015-02-24 11:35:41 -0800,,
14445,570306133677760513,neutral,1.0000,,,Virgin America,,cairdin,,0,@VirginAmerica What @dhepburn said.,,2015-02-24 11:35:52 -0800,,Eastern Time (US & Canada)
14446,570306217001799680,negative,0.3475,Can't Tell,0.3475,United,,samidip,,0,@united Your ERI-ORD express connections are h...,,2015-02-24 11:36:12 -0800,"Erie, PA",Eastern Time (US & Canada)
14447,570306250442985473,negative,1.0000,Flight Booking Problems,0.3448,American,,CathiKingWarren,,0,@AmericanAir it's not just frustrating--it was...,,2015-02-24 11:36:20 -0800,"San Antonio, Republic of Texas",
14448,570306260010176512,negative,1.0000,Flight Booking Problems,0.3488,American,,HollyKinnamon,,0,@AmericanAir 1hr 46 min. Cost of flight change...,,2015-02-24 11:36:22 -0800,"Washington, DC",Quito
14449,570306423818723328,neutral,0.6767,,0,American,,sammy575,,0,@AmericanAir is the new 9:45 time confirmed or...,,2015-02-24 11:37:01 -0800,New York,Eastern Time (US & Canada)
14450,570306529947193344,negative,0.6449,longlines,0.334,American,,TheTPVshow,,0,@AmericanAir I slept in the miami airport due ...,,2015-02-24 11:37:27 -0800,MN,Central Time (US & Canada)
14451,570306662575300611,neutral,0.6742,,,American,,gjeaviation,,0,@AmericanAir 767 seconds from touchdown at Mad...,,2015-02-24 11:37:58 -0800,"Worcester, UK",London
14452,570306715599695874,negative,0.6889,Can't Tell,0.3444,American,,banderson_1978,,0,@AmericanAir Mold on my flight?!? US3825 #filt...,"[35.22643463, -80.93879965]",2015-02-24 11:38:11 -0800,"Albany, NY",
14453,570306715880706049,negative,1.0000,Bad Flight,0.6505,US Airways,,Anthony_Scerri,,0,@USAirways flight 645 to Phoenix deboards pass...,,2015-02-24 11:38:11 -0800,"Astoria, NY",Quito
14454,570306733010264064,positive,0.3441,,0,United,,rombaa,,0,@united thanks -- we filled it out. How's our ...,,2015-02-24 11:38:15 -0800,,
14455,570306867135696897,neutral,1.0000,,,US Airways,,AshleyKAtherton,,0,@USAirways agree! Richard P. Literally ripped ...,,2015-02-24 11:38:47 -0800,,Central Time (US & Canada)
14456,570306867878072320,negative,1.0000,Flight Attendant Complaints,1,American,,TheTPVshow,,0,@AmericanAir aa employees were rude and unwill...,,2015-02-24 11:38:47 -0800,MN,Central Time (US & Canada)
14457,570307011981783040,positive,1.0000,,,US Airways,,noelzucchero,,0,@USAirways we were moved to a delta direct. Th...,,2015-02-24 11:39:22 -0800,,Eastern Time (US & Canada)
14458,570307026263384064,negative,1.0000,Late Flight,1,United,,lsalazarll,,0,@united Delayed due to lack of crew and now de...,,2015-02-24 11:39:25 -0800,,Mountain Time (US & Canada)
14459,570307109218340865,negative,0.7020,Flight Attendant Complaints,0.702,US Airways,,jeremyleewhite,,0,@USAirways is not the new @AmericanAir is more...,"[35.21979387, -80.94498281]",2015-02-24 11:39:45 -0800,,
14460,570307109704900608,negative,1.0000,Cancelled Flight,0.703,United,,CoralReefer420,,0,@united still no refund or word via DM. Please...,,2015-02-24 11:39:45 -0800,"Bay Area, California",Alaska
14461,570307312675651585,positive,0.6604,,,American,,bharris77,,0,"@AmericanAir Believe me, I understand. Flight ...",,2015-02-24 11:40:33 -0800,"Frisco, Texas",Central Time (US & Canada)
14462,570307369328095232,negative,0.6670,Customer Service Issue,0.3341,American,,Bossman1908,,0,"@AmericanAir sorry so Late Flight, responded t...",,2015-02-24 11:40:47 -0800,Liverpool,
14463,570307390752608257,negative,1.0000,Flight Booking Problems,0.6796,American,,barbararwill,,0,"@AmericanAir no thanks. As I said, being deni...",,2015-02-24 11:40:52 -0800,Mexico City,
14464,570307434113310720,negative,0.6547,Late Flight,0.3331,American,,LauraMolito,,0,"@AmericanAir stranded for 24 hours in MIA, Pat...",,2015-02-24 11:41:02 -0800,"New York, NY",Atlantic Time (Canada)
14465,570307605631012864,negative,1.0000,Customer Service Issue,1,US Airways,,Matt_Bernanke,,0,@USAirways you're killing me from the inside,,2015-02-24 11:41:43 -0800,,Quito
14466,570307615189835777,negative,1.0000,Customer Service Issue,1,Southwest,,cindyjwhitaker,,0,@SouthwestAir Hello - been on hold for extreme...,,2015-02-24 11:41:45 -0800,,Central Time (US & Canada)
14467,570307820962373632,negative,1.0000,Flight Attendant Complaints,0.6522,Delta,,Oneladyyouadore,,0,"@JetBlue They weren't on any flight, they just...",,2015-02-24 11:42:34 -0800,Georgia,Quito
14468,570307847281614848,positive,1.0000,,,United,,CoreyAStewart,,0,@united Thanks for taking care of that MR!! Ha...,,2015-02-24 11:42:41 -0800,"Richmond, VA",Eastern Time (US & Canada)
14469,570307876897628160,positive,1.0000,,,United,,rdowning76,,0,@united thanks,,2015-02-24 11:42:48 -0800,usa,
14470,570307948171423745,negative,0.6846,Flight Booking Problems,0.6846,American,,SweeLoTmac,,0,@AmericanAir why would I pay $200 to reactivat...,,2015-02-24 11:43:05 -0800,,Quito
14471,570307949614256128,negative,0.6316,Bad Flight,0.3164,American,,ELLLORRAC,,0,@AmericanAir thanks for getting back to me. Bu...,,2015-02-24 11:43:05 -0800,,Central Time (US & Canada)
14472,570308064185880577,neutral,0.6667,,,American,,LancasterPattie,,0,@AmericanAir we've already made other arrangem...,,2015-02-24 11:43:32 -0800,,
14473,570308156699611137,neutral,1.0000,,,US Airways,,AshleyKAtherton,,0,@USAirways never received such horrible servic...,,2015-02-24 11:43:55 -0800,,Central Time (US & Canada)
14474,570308309682675712,negative,1.0000,Customer Service Issue,1,American,,SweeLoTmac,,0,@AmericanAir why would I even consider continu...,,2015-02-24 11:44:31 -0800,,Quito
14475,570308513181904901,neutral,1.0000,,,Delta,,Oneladyyouadore,,0,"@JetBlue flight 1041 to Savannah, GA",,2015-02-24 11:45:20 -0800,Georgia,Quito
14476,570308799950692353,negative,1.0000,Customer Service Issue,0.6452,US Airways,,retardedlarry,,0,@USAirways just hung up on me again. Another ...,,2015-02-24 11:46:28 -0800,,
14477,570309000279023616,neutral,1.0000,,,US Airways,,AshleyKAtherton,,0,@USAirways Fortunately you have staff like Lyn...,,2015-02-24 11:47:16 -0800,,Central Time (US & Canada)
14478,570309145276125185,negative,0.6361,Cancelled Flight,0.6361,Southwest,,tomcblock,,0,@SouthwestAir although I'm not happy you Cance...,,2015-02-24 11:47:50 -0800,"ÜT: 38.965477,-77.428287",Eastern Time (US & Canada)
14479,570309156290367488,negative,1.0000,longlines,0.6624,Southwest,,thisradlove,,0,@SouthwestAir still waiting. Just hit one hour.,,2015-02-24 11:47:53 -0800,Today I'm in: Maryland,Atlantic Time (Canada)
14480,570309308937842688,neutral,0.6869,,,Delta,,Oneladyyouadore,,0,@JetBlue I hope so because I fly very often an...,,2015-02-24 11:48:29 -0800,Georgia,Quito
14481,570309340952993796,neutral,1.0000,,,US Airways,,DebbiMcGinnis,,0,@USAirways is a DM possible if you aren't foll...,,2015-02-24 11:48:37 -0800,Missourah,Hawaii
14482,570309345281486848,positive,0.6469,,,Delta,,jaxbra,,0,@JetBlue Yesterday on my way from EWR to FLL j...,,2015-02-24 11:48:38 -0800,"east brunswick, nj",Atlantic Time (Canada)
14483,570310144459972608,negative,1.0000,Customer Service Issue,1,US Airways,,GAKotsch,,0,@USAirways and when will one of these agents b...,,2015-02-24 11:51:48 -0800,,Atlantic Time (Canada)
14484,570310600460525568,negative,0.6292,Flight Booking Problems,0.3146,US Airways,,jhazelnut,,0,@USAirways is there a better time to call? My...,,2015-02-24 11:53:37 -0800,,

In [52]:
#dealing with categorical data
#create dummy variables for sentiment toward airlines
dum_sent = pd.get_dummies(airline_sentiment)

NameError: name 'airline_sentiment' is not defined

In [53]:
#create dummy variables for specific airlines and combine into one data frame
dum_air = pd.get_dummies(airline)
airline_df = pd.concat([airline_df, dum_air], axis=1)

NameError: name 'airline' is not defined

In [54]:
airline_df = pd.concat([airline_df, dum_sent], axis=1)
#summary statistics with new dummy variables
airline_df.describe()

NameError: name 'dum_sent' is not defined

In [49]:
#value counts for each of the airline dummies
airline_df['airline_American'].value_counts()

KeyError: 'airline_American'

In [ ]:
airline_df['airline_Delta'].value_counts()

In [ ]:
airline_df['airline_Southwest'].value_counts()

In [ ]:
airline_df['airline_US Airways'].value_counts()

In [ ]:
airline_df['airline_United'].value_counts()

In [ ]:
airline_df['airline_Virgin America'].value_counts()

In [ ]:
#value counts for each of the three types of sentiment towards the airline
airline_df['airline_sentiment_negative'].value_counts()

In [ ]:
airline_df['airline_sentiment_neutral'].value_counts()

In [ ]:
airline_df['airline_sentiment_positive'].value_counts()

In [ ]:
#visualizing data

In [ ]:
sns.lmplot(x="airline_Delta", y="airline_United", data=airline_df)

In [ ]:
sns.lmplot(x="airline_Delta", y="airline_American", data=airline_df)

In [ ]:
sns.lmplot(x="airline_Delta", y="airline_Southwest", data=airline_df)

In [ ]:
sns.lmplot(x="airline_Delta", y="airline_sentiment_negative", data=airline_df)

In [ ]:
sns.lmplot(x="airline_Delta", y="airline_sentiment_neutral", data=airline_df)

In [ ]:
sns.lmplot(x="airline_Delta", y="airline_sentiment_positive", data=airline_df)

In [26]:
# CSV !!!!
#naming columns for first data set, a csv file
names = ['Wife\'s age', 'Wife\'s education', 'Husband\'s education', 'Number of children ever born',
        'Wife\'s religion', 'Wife\'s now working', 'Husband\'s occupation', 'Standard-of-living index',
        'Media exposure', 'Contraceptive method used']

In [25]:
#reading in csv data
cmc_df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/cmc/cmc.data",
                       header=None, names=names)

In [24]:
cmc_df.head()

,Wife's age,Wife's education,Husband's education,Number of children ever born,Wife's religion,Wife's now working,Husband's occupation,Standard-of-living index,Media exposure,Contraceptive method used
0,24,2,3,3,1,1,2,3,0,1
1,45,1,3,10,1,1,3,4,0,1
2,43,2,3,7,1,1,3,4,0,1
3,42,3,2,9,1,1,3,3,0,1
4,36,3,3,8,1,1,3,2,0,1

In [ ]:
#summary stats for cmc_df data set (csv file)
cmc_df.describe()

In [ ]:
cmc_df.info()

In [ ]:
cmc_df['Number of children ever born'].unique()

In [ ]:
cmc_df['Contraceptive method used'].unique()

In [ ]:
cmc_df['Wife\'s age'].unique()

In [ ]:
cmc_df['Wife\'s education'].unique()

In [ ]:
cmc_df['Husband\'s education'].unique()

In [ ]:
cmc_df['Wife\'s religion'].unique()

In [ ]:
cmc_df['Media exposure'].unique()

In [ ]:
%matplotlib inline

In [ ]:
cmc_df.info()

In [ ]:
#showing outliers
abox = cmc_df['Wife\'s age'].plot(kind="box")

In [ ]:
bbox = cmc_df['Wife\'s education'].plot(kind="box")

In [ ]:
cbox = cmc_df['Husband\'s education'].plot(kind="box")

In [ ]:
dbox = cmc_df['Number of children ever born'].plot(kind="box")

In [ ]:
ebox = cmc_df['Wife\'s religion'].plot(kind="box")

In [ ]:
fbox = cmc_df['Wife\'s now working'].plot(kind="box")

In [ ]:
gbox = cmc_df['Husband\'s occupation'].plot(kind="box")

In [ ]:
hbox = cmc_df['Contraceptive method used'].plot(kind="box")

In [ ]:
#i will consider outliers on all variables--although there aren't many
q_df = cmc_df.quantile([.25, .75])
q_df.loc['iqr'] = q_df.loc[0.75] - q_df.loc[0.25]
q_df.loc['whisker_length'] = 1.5 * q_df.loc['iqr']
q_df.loc['max_whisker'] = q_df.loc['whisker_length'] + q_df.loc[0.75]
q_df.loc['min_whisker'] = q_df.loc[0.25] - q_df.loc['whisker_length']
q_df

In [ ]:
#i will reconsider potential outliers under "Number of children ever born" using Std dev. method
std_children = cmc_df['Number of children ever born'].std()
std_children

In [ ]:
max_outlier_children_value = cmc_df['Number of children ever born'].mean() + (std_children * 3)
max_outlier_children_value

In [ ]:
#from the chart, still dealing with outliers under "Number of children ever born"
max_outlier_children = [num for num in cmc_df['Number of children ever born'] if num > q_df['Number of children ever born'].loc['max_whisker']]
len(max_outlier_children)

In [ ]:
#the numbers given to us are vastly different; most likely due to there not being very much variety in datapoints

In [ ]:
#for further clarity I'll check how many of each value there are for some variables
cmc_df['Wife\'s age'].value_counts()

In [ ]:
cmc_df['Number of children ever born'].value_counts()

In [ ]:
#here is a correlation chart of variables
cmc_df.corr()

In [ ]:
#here is additional summary statistics table with additional percentiles added
cmc_df.describe(percentiles=[.01, .05, .95, .99])

In [ ]:
#i will now visualize the data

In [ ]:
sns.lmplot(x="Wife\'s age", y="Number of children ever born", data=cmc_df)

In [ ]:
sns.lmplot(x="Wife\'s age", y="Contraceptive method used", data=cmc_df)

In [ ]:
sns.lmplot(x="Wife\'s education", y="Husband\'s education", data=cmc_df)

In [ ]:
sns.lmplot(x="Number of children ever born", y="Wife\'s religion", data=cmc_df)

In [ ]:
sns.lmplot(x="Wife\'s now working", y="Contraceptive method used", data=cmc_df)

In [ ]:
sns.lmplot(x="Wife\'s education", y="Contraceptive method used", data=cmc_df)